### ISSUE TITLE
Skeny dokladů - další funkce

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1056]
Jde nahrávat skeny dokladů, ale zatím se s tím moc dobře nepracuje.  Tady sepisuji návrhy co zlepšit/přidat.

- označit u kterých dokladů jsou skeny
- hromadné stažení dokladů k akci
- stažení všech dokladů k vybraným akcím?

Otázky:
- jak se mají třídit soubory nebo jak je prejmenovat aby bylo jasné který doklad patří kam?

**Comment by vojta001** [comment]
Za mě ještě: náhledy scanů (teda není-li to příliš složité, původně měli být scany na GDrive, tam to je atribut souboru) a namísto označení, zda-li scan k dokladu je, rovnou napsat kolik jich je.

**Comment by Huron32** [comment]
Jak se na to úložiště na Gdoc dostanu? Bude vytvořen nějaký prostor přístupný dané jednotce? Nebo se k tomu půjde dostat pouze "proklikem"v h.skautingu? Omezení velikosti?

**Comment by kalich5** [comment]
@Huron32 podle mě jediné smysluplné řešení je pouze proklik z h.skautingu. Velikost je podle mě dostatečná v řádu několika mega. Větší obrázky stejně nemají smysl.

**Comment by Huron32** [comment]
> @Huron32 podle mě jediné smysluplné řešení je pouze proklik z h.skautingu. Velikost je podle mě dostatečná v řádu několika mega. Větší obrázky stejně nemají smysl.

OK, jen to je uživatelsky poněkud  "nepohodlné" - nutnost rozklikávat každý doklad a stahovat ručně...Přístup do jednoho adresáře by byl IMHO lepší.
