### ISSUE TITLE
Výchozí řazení akcí

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1093]
Nastavit řazení dle začátku akce, názvu jako výchozí řazení výprav.

**Comment by kalich5** [comment]
Akce by se měly řadit chronologicky ve výchozím stavu. Né podle názvu.

**Comment by sinacek** [comment]
Chronologicky podle založení?

**Comment by kalich5** [comment]
ne, podle toho jak se konají

**Comment by sinacek** [comment]
`začátku akce, názvu` bylo myšleno jako řazení postupně podle další parametrů při shodě:

1. začátku akce
2. názvu

**Comment by kalich5** [comment]
Řazení pouze podle datumů, názvy do toho vůbec nemotej
