### ISSUE TITLE
Import a (aktualizace) akcí z Google kalendáře

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1094]
Máme v Google kalendáři zadané všechny akce a uvital bych, aby byl možnost hromadně importovat akce z kalendáře. Přes API co k tomu Google má https://developers.google.com/calendar

Mít vytvořenou jednu Google aplikaci, která by byla přímo integrovaná v hospodaření. 

### IMPORT
1. U akcí mít tlačítko IMPORT a po jeho stisknutí by se objevila stránka, kde by se uživatel přihlásil přes svůj Google účet, kde má kalendáře.
2. Dále by si vybral, ze kterého kalendáře chce události synchronizovat.
3. Mít možnost nastavit si, od kdy do kdy.
4. Zobrazit, co všechno se importuje. (název, datum), další nastavení jako pořádající jednotka, rozsah, typ a možnost zadat prefix pro účetnictví.
5. Následně kliknout na import a v hospodaření se vytvoří jednotlivé akce.

### AKTUALIZACE
1. U akcí by bylo tlačítko AKTUALIZOVAT a přes něj by proces probíhal stejně.
2. Přihlásit se, vybrat kalendář, od kdy do kdy.
3. Následně by Hospodaření zobrazilo, jaké jsou změny u akcí. Které jsou třeba zrušené, kde se změnilo datum, název akce.
4. U každého řádku by byly tlačítka. (Ponechat/Aktualizovat/Smazat)

Hodně jednotek Google kalendáře používá a tohle by ulehčilo překopírovávání akcí. A mohl by si to dělat třeba i hospodář, pokud by měl kalendáře jednotek pro čtení.

**Comment by sinacek** [comment]
Zajímavý nápad ale vidim to jako spatny pomer cena/vykon

**Comment by fmasa** [comment]
@kalich5 Kolik takových akcí ročně zhruba máte?

**Comment by kalich5** [comment]
No každých 14 dní jsou akce o víkendu. Ty by tam měly být. A máme 6 oddílů, které to takhle mají. Do toho máme třeba 3-5 střediskových celovíkendovek.
To může být tak 30-40 akcí za rok na oddíl. Berme střed 35 x 6 = 210 plus nějaké střediskové akce. Každý oddíl má Google kalendáře kam píše akce se srazy. 
Tohle by tedy ulehčilo zadávání.

**Comment by kalich5** [comment]
A pro začátek určitě stačí jen ten IMPORT. Ta aktualizace je něco navíc.

**Comment by sinacek** [comment]
Kolik máš jich reálně účtovaných v hospodaření z toho? 210 za vaše středisko mi přijde neuvěřitelné číslo

**Comment by kalich5** [comment]
Chci se zbavit černých fondů a všechny akce kde se něco vybírá od účastníků řešit transparentně. Takže když z toho vyházíme nějaké akce po Praze a v okolí kam stačí legitka. Bude jich třeba 120-150 ročně.

**Comment by sinacek** [comment]
A to jediné co tomu brání je import? chápu, že je to zjednodušení, ale pokud to teďka nepoužíváte, tak tohle neberu jako blocker.

**Comment by kalich5** [comment]
Budeme s tím začínat, takhle teď to nic neblokuje. Jen když jsem nad tím přemýšlel, tak by tohle mohlo být zajímavé usnadnění práce. Protože něco v dnešní době přepisovat je divný. Když systémy mají API.

Docela by mě zajímalo, kolik lidí by tohle využilo.

**Comment by kalich5** [comment]
Šlo by tohle vyvěsit na FB h.skautingu... Mohlo by být zajímavé zjistit, jestli by to využili i lidi, co tam ty akce teď řeší.

**Comment by sinacek** [comment]
Založit akci trvá cca 1 minutu. Kdyz vezmu těch 150 akcí tak jsou to max 3 hodiny práce za rok za celé středisko, což mi příjde zanedbatelné vůči libovolné jiné části agendy, kterou tady optimalizujeme.

Že existují API chápu a kdo bude chtít tak to může dopsat, za mě je to minimální přínos.

**Comment by fmasa** [comment]
@kalich5 Obecně si myslím, že je lepší si dopsat něco, co bude nalévat data Google Kalendář -> Skautis. Nebo ještě lépe Skautis -> Google Kalendář, to je třeba skvělá feature přímo pro Skautis.
Tím, že tebou popisované detaily akce přebíráme ze Skautisu, to IMO do Hospodaření nepatří.

**Comment by kalich5** [comment]
Podle mě patří, protože zadávat každou akci mimo město, nebo víkendovku do skautISu je prostě neefektivní.

**Comment by fmasa** [comment]
@kalich5 Ale každá akce v Hospodaření je zároveň akce ve Skautisu, takže vytvoření akce v Hospodaření není nic jinýho než použití jinýho frontendu pro založení akce ve Skautisu. Proto si myslím, že Hospodaření není místo, kde by tohle mělo být implementováno.

**Comment by kalich5** [comment]
Jako to, aby se přidalo tohle na straně skautISu, je vlastně nemožné. Proto mi přijde lepší to řešit tady. Přeci jen by to nemuselo být až tak složité na implementaci.

**Comment by fmasa** [comment]
@kalich5 Jak jsem psal. Import Google Kalendář -> Skautis/Hospodaření mi nedává smysl. Ve Skautisu/Hospodaření bych je výrazně víc strukturovaných informací než jsme schopni dostat z Kalendáře, takže pro většinu . Proto mi přijde lepší varianta vše držet ve Skautisu/Hospodaření a dopsat nástroj na export do Kalendáře.

**Comment by fmasa** [comment]
@sinacek Tvůj názor?

Za mě je to mimo záběr Hospodaření. Jsem schopen nějak vypomoct, pokud by to byl samostatnej projekt.

**Comment by sinacek** [comment]
Nepříjde mi to jako součást hospodaření i když to může být užitečné pro určitou skupinu. Ale nemůžeme dělat v hospodaření vše, co nám ve skautisu chybí.

Směr importu bych viděl taky raději ze skautisu do googlu z toho důvodu jak psal fmasa, ze ve skautisu je více informací a jen podmnožina jde do google kalendáře.
