### ISSUE TITLE
Prefix při zadávání akce

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1103]
Není možné při zadání nové akce vyplnit prefix. To pavažuji za zásadní chybu. Možnost vyplňovat to někde v akci je hloupost. A je to moc kliků a je to zastrčené. Uvítal bych, aby okénko na vyplnění prexifu bylo už při zakládání akce.

**Comment by kalich5** [comment]
Tahle možnost tam byla, ale zmizela. Tak bych uvítal, aby se vrátila. Měla by to být rychlá úprava.

**Comment by fmasa** [comment]
> Měla by to být rychlá úprava.
Jo?

**Comment by kalich5** [comment]
jo :D bylo to tam a před nějakou dobou to zmizelo, nechápu proč, stejně jako třeba Maru. Tak bychom uvítali, aby to bylo zpátky.

**Comment by manulekonecna** [comment]
Ahoj Kalichu, 
procházím nedořešené tasky, tak přidávám komentář. 

U prefixů došlo ke sjednocení s tábory a nyní se to zadává na kartě Evidence plateb. Problém je, že tábory se zakládají přes skautIS, kde se žádný Prefix nevypisuje. Řešili jsme to se Sinem, jak to udělat, ale nedošli jsme k jednoduchému závěru, jak píšeš. 
 
Ohledně Prefixů máme od uživatelů požadavky - ideální by bylo, kdyby:
1) při zadávání nové akce bylo možné Prefix nastavit. Je potřeba dořešit, co s tábory - že by se toto dalo nastavit přímo v základních údajích - nicméně bude to pak jediná doplňková věc, která se bude upravovat v h.skautingu a ne ve skautIS.

2) U evidence plateb chceme, aby zůstalo Tlačítko "Prefix", aby uživatel viděl, jaký Prefix je zadaný a případně rovnou viděl, kde to upravit. 

Teoreticky by tlačítko mohlo vést i na jinou stránku - kartu "základní údaje" , kde by se Prefix nastavil a na Evidenci plateb by se pouze zobrazoval.. Ale jak píšu výše, zatím nemáme jasno a je potřeba, aby to kluci promysleli.

**Comment by sinacek** [comment]
Nyni je prefix oddělený pro pokladnu a pro banku, coz mi v tu chvili nedava smysl to vyplnovat při zakládání ty 2 udaje.
Vidim to i jako různé role. Zaklada akci nekdo se seznamem akci a klidne bez hospodářské znalosti. Kde to pouzivaji tak ten co resi doklady i doplni prefixy
