### ISSUE TITLE
Zobrazování Akcí + filtrování

### ISSUE THREAD

**Issue by Huron32** [skaut/Skautske-hospodareni#1130]
### Popiš chybu
V přehledu Akcí se nedají "vypnout" filtry, resp. nepřišel jsem na to jak. 
Po přihlášení do systému a kliknutí na záložku Akce mi to defaultně načte všechny ROZPRACOVÁNO.
Nicméně když přepnu na NEZRUŠENÉ (abych si zobrazil všechny naše akce, tak potom si je nemůžu seřadit třeba podle jména....protože když kliknu na příslušné řazení, tak se mi to znova načte a současně tam znova naskočí filtr s ROZPRACOVÁNO s hláškou, že nebyly nalezeny žádné akce, ať zkusím zrušit filtry...

Dělám něco blbě? 

Díky

### Uživatelské informace:
 - Sekce: AKCE
 - Uživatelská role: vedoucí/admin střediska 114.32

**Comment by sinacek** [comment]
koukal jsem na to a nechová se to správně. @fmasa můžeš na to kouknout jak jsi to tam propojoval?
