### ISSUE TITLE
Export banky do hromadného exportu akcí a do táborů

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1144]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
Aktuálně v Excelovém souhrnu akcí (a táborů) není exportována Banka.

### Popiš tvůj návrh řešení
A) Do listu doklady exportovat vše a přidat sloupec cash/bank.

B) Udělat nový list Banka, který bude stejný jako list Doklady ale bude obsahovat jen doklady z banky.

### Prostor pro další poznámky, snímky obrazovky či alternativní řešení
Je to potřeba udělat rychle, aby se snáze zpracovaly výpravy před koncem roku.

**Comment by sinacek** [comment]
@fmasa ?

**Comment by fmasa** [comment]
Za mě osobně zní b) lépe. Zároveň však tu funkci nepoužíváme, tak netuším, jestli se hodí a)

**Comment by sinacek** [comment]
mě příjde varianta A, ze je flexibilnější. mohu secist vse napric kategoriemi bez toho abych to mel na 2 listech apod.

**Comment by krystofkomarek** [comment]
ahoj kluci, experti jste vy, ale a) mi přijde elegantnější řešení.
samostatný list pro banku a pro cash nemá pro nás využití a vedlo by to stejně k tomu, že bychom ten druhý list kopírovali do prvního.
díky moc, že se tím zabýváte.

**Comment by fmasa** [comment]
Jak jsem psal, my to nepoužíváme, tak nemůžu soudit. :slightly_smiling_face:  Pojďme tedy cestou a) :+1:

**Comment by krystofkomarek** [comment]
prima, souhlas, díky!!
