### ISSUE TITLE
Nelze odeslat informace o platbě. Error 503

### ISSUE THREAD

**Issue by juradee** [skaut/Skautske-hospodareni#1145]
### Popiš chybu
Nelze odeslat hromadná pošta s pokyny pro platu. Emailů je 70,  na třetí pokud se akce dokončila . 

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci 'platby'
2. Klikni na 'rozeslat emaily'
3. následuje error 503

### Očekávané chování
Příklad: odešle se pošta

### Uživatelské informace:
 - Sekce: (Platby)
 - Uživatelská role: vedoucí/admin oddílu 622.093

**Comment by sinacek** [comment]
Ahoj,
tam si myslím, že to bude timeout na čem to spadne a nevím jestli s tím dokážeme moc víc udělat. Vzdy se odesle cast zprav a ty se oznaci jako odeslané, tedy kdyz to udelas několikrat tak se dostanes ke správnému výsledku. Jeste bych to tu nechal abychom se podivali jak to můzeme lépe popsat(vypsat co se stalo) apod a ne jen chybu 503

**Comment by juradee** [comment]
Ideálním řešením je použit nějakou službu na odesílání pošty, například mailgun. Nebo tam udělejte frontu a posílejte poštu cronem ať nejste omezeni časem zpracování a nebo to stejné přes Rabitta. 70 emailů není mnoho na to aby to takovýto systém nedokázal ustát. Pokud by jste chtěli konzultaci, jsem k dispozici.

**Comment by fmasa** [comment]
@juradee Odesíláme z SMTP serverů, které nejsou naše (střediska si je přidávají samy). My můžeme navýšit timeout, ale ve výsledku to stejně bude stát na odpovědi SMTP.  Proto Mailgun ani jiná vlastní služba není úplně řešením.

Cron je určitě varianta, Rabbit na [Lebedě](https://lebedahosting.cz/) bohužel nemáme.

Každopádně jsi schopen poslat název vašeho mailu v Hospodaření?

@sinacek Minimálně jsem přemýšlel, jestli nepřipravit kromě podpory SMTP přímo integraci Gmailu, posílání přes jejich API by mohlo být rychlejší + by šlo používat několik paralelních requestů.

**Comment by juradee** [comment]
Používáme stmp na gmailu na skautské doméně platby@strediskorm.cz
