### ISSUE TITLE
Google ukončí podporu aplikací používajících heslo pro přístup k účtu

### ISSUE THREAD

**Issue by fmasa** [skaut/Skautske-hospodareni#1179]
Gmail pro rozesílání emailů používá 83 z 87 SMTP přístupů, které v Hospodaření uživatelé mají. Google [oznámil ukončení podpory pro "Méně zabezpečené aplikace" (LSA) u G Suite účtů](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html). To je možnost, která aktuálně musí být povolená, aby bylo možné použít username a heslo ke Google účtu pro plain SMTP autentizaci.

Sice tam není explicitně zmíněný SMTP protokol, ale tím, že se jedná o LSA obecně, tak jde předpokládat, že nepůjde používat také (další protokoly, které se používají pro přístup k Gmailu jako např. IMAP jsou přímo zmíněné).

- od 15. června 2020 G Suite účty, které LSA dříve nepoužili, nebudou moct LSA používat
- od 15. února 2021 nebudou žádné G Suite účty moct LSA používat

To znamená, že bychom se měli zamyslet, jak to vyřešit. Jako nejlepší varianta mi přijde, přidat kromě SMTP podporu pro propojení s Google účtem přes OAauth a následné odesílání přes Gmail API.

**Comment by fmasa** [comment]
@sinacek Tohle by IMO stálo za to přidat do 2020Q1

**Comment by sinacek** [comment]
Určitě souhlas, jen zatím nevím kolik to bude práce a jak to realizovat.

**Comment by sinacek** [comment]
@fmasa Send email je v sekci `sensitive` https://developers.google.com/gmail/api/auth/scopes coz pak může vést k tomu, že google bude muset prověřit naší aplikaci. Máš s tím nějakou zkušenost?

**Comment by sinacek** [comment]
Použijeme to jako internal a pak nepotřebujeme schválení a není tam limit na počet uživatelů.

**Comment by marekdedic** [comment]
Ahoj, proklikal jsem se sem po webináři - chtěl jsem navrhnout, zda nepřidat možnost připojit Google účet skrz Google aplikaci namísto toho, aby tam uživatelé museli vyplňovat SMTP...

Něco podobného jsem řešil do WordPressu a použil jsem plugin [awesomemotive/wp-mail-smtp](https://github.com/awesomemotive/wp-mail-smtp) - třeba by se tam dalo inspirovat... :)

Díky!

**Comment by fmasa** [comment]
@marekdedic Myslíš tím tedy přihášit se přes OAuth (tedy mít vlastní Google appku) a odesílat přes API?

To je zřejmě cesta, kterou půjdeme :slightly_smiling_face: Je to asi jedinná rozumná varianta, která výrazně nesníží (spíš naopak) komfort uživatelů.

**Comment by marekdedic** [comment]
@fmasa - přesně tak, mít vlastní Google appku a posílat přes API. Tedy uživatel v h.skautingu klikne na tlačítko "propojit", to ho pošle na Google, kde potvrdí práva pro tu aplikaci a tím má hotovo. Jak píšeš, pro uživatele to bude jednodušší.
