### ISSUE TITLE
Chyba při načítání Fio plateb, kdy platba nemá vyplněný typ transakce

### ISSUE THREAD

**Issue by fmasa** [skaut/Skautske-hospodareni#1181]
### Popiš chybu
Nedaří se párovat platby, pokud nějaká z Fio transakcí nemá vyplněný typ transakce 

https://sentry.io/organizations/skautske-hospodareni-of/issues/1406434760/events/b6a4844106fe48fa8567974770e2b0e4/?project=1328535&query=is%3Aunresolved

### Očekávané chování
Platby se normálně spárují.

### Snímky obrazovky
\-

### Uživatelské informace:
 \-

**Comment by fmasa** [comment]
@sinacek Poslal jsem PR do knihovny, kterou používáme (https://github.com/mhujer/fio-api-php/pull/19)

**Comment by mhujer** [comment]
@fmasa díky za fix, rovnou jsem tagnul 4.1.2, takže můžeš updatnout.

**Comment by fmasa** [comment]
Díky moc :+1:

**Comment by sinacek** [comment]
updated by #1182
