### ISSUE TITLE
Upomínka platby

### ISSUE THREAD

**Issue by juradee** [skaut/Skautske-hospodareni#1211]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.

Pokud je platba již po splatnosti, nelze odeslat email s upomínkou. Upomínka se musí odeslat ručně a po jednom. Neexistuje šablona emailu pro upomínku. Odešle se pravděpodobně email s pokyny pro platbu, který šel s prvním odesláním. 

### Popiš tvůj návrh řešení

Přidat šablonu pro odeslání upomínky.
Přidat stav odeslaná upomínka
Přidat hromadnou akci odeslat upomínku. Email se odešle všem, kteří mají již platbu po splatnosti.

**Comment by fmasa** [comment]
@juradee Tohle už evidujeme v https://github.com/skaut/Skautske-hospodareni/issues/61, takže bych ideálně tu issue rozšířil o možnost hromadného odeslání upomínek, co myslíš?

**Comment by juradee** [comment]
Souhlas. Možná bych tam připsal možnost zadat tam extra šablonu pro upomínku. Přece jen text prvního emailu a upomínky bývá odlišný

**Comment by sinacek** [comment]
doplnil jsem to do popisu #61 a uzavírám jako duplicitní
