### ISSUE TITLE
Kopírování řádků v cesťácích

### ISSUE THREAD

**Issue by jan-stanek** [skaut/Skautske-hospodareni#1215]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
U táborů se dost často opakují stejné cesty (denní nákupy, ...), hodila by se možnost zduplikovat řádek a pak jen upravit datum (ideálně rovnou inline).

### Popiš tvůj návrh řešení
Stačilo by přidat tlačítko pro zduplikování řádku.

### Prostor pro další poznámky, snímky obrazovky či alternativní řešení
Zkusím na to udělat PR

**Comment by fmasa** [comment]
Implementováno v https://github.com/skaut/Skautske-hospodareni/pull/1255
