### ISSUE TITLE
Nesprávný výpočet věku účastníků

### ISSUE THREAD

**Issue by mrakapet** [skaut/Skautske-hospodareni#1216]
Na stránce "Základní údaje" o akci v bloku se statistikami o účastnících se špatně vypočítávají počty účastníků v dané věkové kategorii.

Na akci jsme měli 1 osobu, které bylo přesně 18 let, ale řadilo jí to stále do kategorie "do 18 let" a "pod 18 let". Podle mě je buď špatně výpočet věku, nebo bych doporučil upravit popisky, aby to nemátlo. A jestli je to takhle naschvál, tak se omlouvám za zmatky.

Ještě doplním, že výpočty všech ostatních hodnot v bloku se statistikami se chovají stejně.

Příklad akce: https://h.skauting.cz/akce/9918.

**Comment by sinacek** [comment]
Toto je přebíráno ze skautisu viz https://is.skaut.cz/Junak/Events/General/General/ParticipantStatistic.aspx?ID=9918 tedy se obrať na podpora@skaut.cz a zeptej se na tu stranku skautisu, co jsem ti sem poslal.

FYI @manulekonecna
