### ISSUE TITLE
Podbarvení testovací verze žlutě

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1217]
Označit pozadí testovací verze `test-h.skauting.cz` žlutě jako to má testovací skautis pro jasnější orientaci, kde se pohybuji.

**Comment by fmasa** [comment]
@sinacek Proč? Testovací verze stejně ve většině případů nepracuje s daty z produkčního Skautisu. Když už, tak bych uvítal tu žlutou barvu jen v případě, že je `testMode: false`, protože jinak je strašně nepříjemný koukat na tu zářivě žlutou barvu.

**Comment by sinacek** [comment]
právě bych to udělal žluté jen když je `testMode: true` ale nevim jestli ses neupsal

**Comment by fmasa** [comment]
Ne, myslel jsem opravdu `testMode: false` + třeba debug mode. Nechci 99% času při vývoji koukat na tu žlutou hrůzu :grinning:

**Comment by sinacek** [comment]
chtěl bych mít jen ten tesh-h.skauting.cz zlutý, tak na něj normalně nekoukáme. tak asi udělat novy parametr, ktety by to nastavil?

**Comment by fmasa** [comment]
Jo tak - tam mi to smysl dává, já bych to jen nerad měl ve své lokální dev verzi

**Comment by sinacek** [comment]
Tomu rozumím. Mas napad jak to udelat v ci? To by bylo asi nejlepší. Rad bych to psojil s tim ze testovaci verzi pak budu propagovat protoze ji lidi malo znaji

**Comment by sinacek** [comment]
@fmasa napad jak to tam dostat v rámci CI?

**Comment by fmasa** [comment]
Parametr třeba `testBackground: false` v config.neon, a v [config.test.local.neon](https://github.com/skaut/Skautske-hospodareni/blob/a1596bf5fe38368e1060e64ba61ecd284155a8d8/app/config/config.test.local.neon) ji nastavovat na `true`

**Comment by sinacek** [comment]
nevim jak to hlavně navázat na sass aby se mi proměnna z config.ci.neon propsala do css
