### ISSUE TITLE
V bootstrapu 4 nefunguje našeptávání osob

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1221]
Pro B4 nefunguje autocomple například ve vedení akce. Zobrazuje se pouze selectbox.

Dále nenapovídá osoby v pokladní knize.

**Comment by fmasa** [comment]
Tohle furt nefunguje, ne<

**Comment by sinacek** [comment]
Ty jsi to upravil aby to byl hezky selectbox jsem myslel

**Comment by fmasa** [comment]
Ale to ještě není ani ve fázi PR 🙂

**Comment by sinacek** [comment]
odhadovaný termín: 1.12.2021

**Comment by sinacek** [comment]
<img width="1713" alt="Screenshot 2022-12-19 at 20 20 49" src="https://user-images.githubusercontent.com/1140123/208503425-a89fd624-4277-49af-a255-4b60bd528b64.png">

https://test-h.skauting.cz/akce/8574/kniha

V libovolné pokladní knize to má nabízet jména členů jednotky jako autocomplete od 2 znaků myslím.

**Comment by sinacek** [comment]
@juradee jak to jde?
