### ISSUE TITLE
Editace položek rozpočtu jednotek

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1259]
Nelze editovat ani mazat položky v rozpočtu **jednotky**.

https://h.skauting.cz/jednotka/budget

**Comment by fmasa** [comment]
To ani předtím nešlo, ne? :grinning: 

Jestli to má být nová featura, tak za mě :-1: - bych dal třeba link do Skautisu, ale nevidím moc přidanou hodnotu v duplikování většího množství funkcionality ze Skautisu, pokud to nejsme schopni udělat lépe.

**Comment by sinacek** [comment]
Ano, ve skautisu rozpocet jednotky není
