### ISSUE TITLE
Export plateb do excelu

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1260]
Přidat možnost exportovat seznam "poptávaných" plateb (založených v systému) do excelu. Kopírování z prohlížeče se nekopíruje dobře s hlavičkou.

**Comment by fmasa** [comment]
Tedy to, co bylo navrženo v https://github.com/skaut/Skautske-hospodareni/issues/772?

**Comment by sinacek** [comment]
Nyní je to v Bootrap 4 a už mi to nefunguje dle původního návodu

**Comment by kalich5** [comment]
Jako bylo by super, to tam mít :-)

**Comment by YuykaS** [comment]
Export plateb by byl super

**Comment by juradee** [comment]
Export plateb by měl být na úrovní přehledu https://h.skauting.cz/platby/, nebo až uvnitř https://h.skauting.cz/platby/skupiny/2038 ?  

Exportovat vždy všechny platby a jejich data, nebo vybírat z tabulky které platby exportovat?

**Comment by sinacek** [comment]
Delal bych to ve skupine a vsechny
