### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1278]
https://sentry.io/organizations/skautske-hospodareni-of/issues/1537678437/?project=1764094&referrer=slack

**Comment by fmasa** [comment]
Problém je v:
https://github.com/skaut/Skautske-hospodareni/blob/24483f4b2ded27ed071ec5a79dcf798b56958784/app/model/Travel/Command.php#L457

Ta metoda má vracet `TransportType[]`, ale vrací `string[]`
