### ISSUE TITLE
Výchozí částky vratek u táborové skupiny plateb

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1325]
U táborové skupiny plateb se jako výchozí částka vratky nabízí zaplacená částka.

**Jak by to mělo být:**
Zobrazit hodnotu vratky v seznamu účastníků tábora. U ostatních 0.

**Comment by fmasa** [comment]
@sinacek Nedává smysl předvyplňovat vždy plnou částku? Tohle mi přijde jako nesystémový řešení.

**Comment by sinacek** [comment]
Pokud jsem u účastníka v systému už zadal, že mu budu vracet 200kč, tak bych čekal, že i zde v záložce vratka mi to nabídne to samé číslo když je dostupné.

**Comment by fmasa** [comment]
@sinacek V tom případě jsme se asi nepochopili. Ty máš na mysli, že pokud u účastníka v modulu `Tábory` vyplním nějakou vratku, tak by mi to mělo tu částku nabízet jako výchozí hodnotu ve vratkách v modulu `Platby`, je to tak?

**Comment by sinacek** [comment]
> @sinacek V tom případě jsme se asi nepochopili. Ty máš na mysli, že pokud u účastníka v modulu `Tábory` vyplním nějakou vratku, tak by mi to mělo tu částku nabízet jako výchozí hodnotu ve vratkách v modulu `Platby`, je to tak?

Ano, protože mi to příjde jako hlavní a skoro jediný správný use case pro vratky u táborů.

**Comment by fmasa** [comment]
V tom případě souhlasím. Jsem myslel, že jsi chtěl předyplňovat částku platby.
