### ISSUE TITLE
Sloučení tlačítek na přidání plateb

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1329]
U skupiny plateb jsou 2 zelená tlačítka na přidání platby.
<img width="1147" alt="Screenshot 2020-04-10 at 20 12 24" src="https://user-images.githubusercontent.com/1140123/79012876-acd96e00-7b67-11ea-9dc1-c2c207dce143.png">
Sjednotil bych je do toho levého, kde by byl nápis 
Přidat platbu:
- obecná
- od člena
- ...

**Comment by fmasa** [comment]
To mi osobně nedává moc smysl. Možná by spíš stálo za to změnit label na *Importovat osoby*

Protože to jsou dost rozdílný věci.

**Comment by sinacek** [comment]
Ja to beru tak ze stale zakladas platby a jen jinym zpusobem. Zadne osoby realne neimportujes

**Comment by fmasa** [comment]
Můžeme to zkusit 🙂

**Comment by sinacek** [comment]
<img width="1198" alt="Screenshot 2020-04-20 at 18 23 35" src="https://user-images.githubusercontent.com/1140123/79775119-0f82f480-8334-11ea-8aaf-ab5071c2e8e0.png"> Takto? @fmasa

**Comment by fmasa** [comment]
@sinacek Přesunul bych to doprava - na původní místo, kde bylo přidání té jedné platby - máme to tak ve všech jiných UI, kde se něco přidává. A chtělo by to najít nějaký lepší názvosloví:
`Přidat osoby ... ze členů` dává smysl, ale `Přidat platbu ... ze členů` moc ne. Možná bych to víc rozepsal a přidal piktogram:

- ![image](https://user-images.githubusercontent.com/5658260/79775592-c7180680-8334-11ea-80ce-d41ccc3c2cbb.png)  Přidat osoby z jednotky
- Přidat obecnou platbu

**Comment by sinacek** [comment]
<img width="1186" alt="Screenshot 2020-04-20 at 20 42 56" src="https://user-images.githubusercontent.com/1140123/79787595-8675b880-8347-11ea-9ac9-d97b3bfeb21d.png">
Přesunul jsem to. Upravil jsem textaci na `Přidat platbu ... za člena, apod`
