### ISSUE TITLE
Pokladní kniha s převodem do pokladny jde mimo

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1337]
Pokladní kniha co obsahuje převod do pokladny, tak má o tlačítko navíc a pak tabulka vylézá z linie stránky

<img width="1260" alt="Screenshot 2020-04-12 at 12 00 22" src="https://user-images.githubusercontent.com/1140123/79066084-4c584700-7cb5-11ea-9e28-0ea24a2c9fb7.png">

**Comment by sinacek** [comment]
@fmasa mas nekde tu rozdělanou verzi s modalem?

**Comment by sinacek** [comment]
@fmasa jak jsi to měl rozmyšlené že by to mělo nově vypadat? Nový doklad půjde do modálu?

**Comment by sinacek** [comment]
@fmasa má PR a je potřeba doladit drobné bugy

**Comment by sinacek** [comment]
odhadovaný termín: 1.12.2021

**Comment by sinacek** [comment]
souvisí s #1077

**Comment by juradee** [comment]
@sinacek @fmasa 
Jako první bych přesunul ten form z leva do horní pozice. Místo col-9 by tak grid byl col-12
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/fc274767-81e7-4806-aa32-e6b66af976f5)

**Comment by juradee** [comment]
Posuvník místo přetečení tabulky
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/6fbaf5c3-d91d-4793-b834-22d2a88d9f3e)

**Comment by ellie-RM** [comment]
krása 👯‍♀️

**Comment by sinacek** [comment]
Chtel bych tohle zkombinovat s tím, že lze ten formulář sbalit, aby nezabiral tolik mista kdyz to clovek nepotrebuje a nemusel scrollovat celou obrazovku dolu. Idealne aby si to pamatovalo po refreshi stranky (napriklad chci donagrat nekolik scanů k dokladům, tak nemusim neustale jezdit dolu s kazdym dalsim scanem).

**Comment by juradee** [comment]
No, ono by to sneslo více věcí. Například editace by mohla být in-line, nebo jako modal.  Přílohy by si zasloužili multiupload. Tabulka by mohla mít filter.

**Comment by sinacek** [comment]
Jo dalších možností je mnoho, to co jsem psal beru jako nutnou součást to přesunu nahoru, proto jsem se fo toho sam nepoustel, protoze to chci dostat rovnou do rozumného stavu a ne to jen presunout. Tedy aspon to skrývání i bez pamatovani.

PS: nejlepší by mi prislo defaulne skrytý formular a u jeho odesílání mit tlačítko "Ulozit a pridat další", coz by po odeslani nechalo formulář rozbaleny

**Comment by sinacek** [comment]
Ok

**Comment by juradee** [comment]
Update: @ellie-RM @sinacek 
schováno
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/ad6f452c-f215-4dc3-a80b-a677ec206ce4)
rozbaleno
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/cbd50b64-326e-4a11-8d12-0d5daf23e706)

**Comment by sinacek** [comment]
Supr, souhlasím. Kdy na tom chces delat? Poslal bych zprávu na fb jako anotaci az bude jasne jak to ma vypadat

**Comment by juradee** [comment]
Mám to nachystané, už jen udělat MR
