### ISSUE TITLE
Neaktualizace tabulky v cesťáku po úpravě hodnoty

### ISSUE THREAD

**Issue by Voclav** [skaut/Skautske-hospodareni#1442]
Když se v upraví datum v ceťáku, tak se neaktualizuje tabulka. Změna se projeví až po aktualizaci stránky.

**Comment by sinacek** [comment]
můžeš popsat o kterou jde tabulku? printscreen apod?

**Comment by Voclav** [comment]
https://h.skauting.cz/cestaky/default/detail/3608

![před úpravou](https://user-images.githubusercontent.com/23616018/89167659-f9641180-d57b-11ea-81d5-5dd85c8b9abe.PNG)
![úprava](https://user-images.githubusercontent.com/23616018/89167657-f832e480-d57b-11ea-862d-159af5918d6c.PNG)
![po úpravě](https://user-images.githubusercontent.com/23616018/89167663-f9fca800-d57b-11ea-84bd-cd65b34ff485.PNG)
![po aktualizaci](https://user-images.githubusercontent.com/23616018/89167662-f9641180-d57b-11ea-8821-445495f6434c.PNG)
