### ISSUE TITLE
Chyba při filtrování cesťáků podle stavu při návratu z casťáku na tabulku všech cesťáků.

### ISSUE THREAD

**Issue by Voclav** [skaut/Skautske-hospodareni#1443]
Když se v tabulce se všemi cesťáky dá filtrovat podle stavu, aby se zobrazily všechny cesťáky, a pak se rozklikne jeden konkrétní cesťák a pak se vrátí zpět na tabulku, tak se v tabulce zobrazí pouze rozpracované cesťáky, i když je stále nastavený filtr na všechny cesťáky.
Aby se mi zobrazily zase všechny cesťáky musím zvolit filtrování podle jiného stavu a pak zase nastavit filtrování zpět na všechny.

**Comment by sinacek** [comment]
Jaký máš prohlížeč? Operační systém?

Já to zkoušel na Firefox 79.0 na Mac OS X a po návratu zpět na tu stránku vidím stav `Rozpracovaný` a tomu odpovídají i položky.

I když jen stránku refreshnu po změně filtru, tak se mi to vrací do základního nastavení s nastavením filtru na `Rozpracovaný`

**Comment by Voclav** [comment]
Chrome a Windows 10.

Po návratu vidím nastavení filtru na Všechny, ale tabulka je filtrovaná podle Rozpracovaný. Po aktualizaci stánky se filtr změní na Rozpracovaný.
