### ISSUE TITLE
Chybná spotřeba u starších vozidel

### ISSUE THREAD

**Issue by Voclav** [skaut/Skautske-hospodareni#1444]
U dříve vytvořených vozidel jsou špatné spotřeby paliva, ale nikde není viditelné upozornění, že se někde v h.skautingu stlala chyba, aby si to uživatelé zkontrolovali. Kdyby mě neupozornil vůdce střediska vůbec bych si toho nevšiml.
Teď budu muset udělat revizi všech cesťáků v učetnictví střediska, které byly vytvořeny přes h.skauting.

**Comment by sinacek** [comment]
Můžeš popsat jak jsou špatně uvedeny spotřeby? tohle není jak zkontrolovat

**Comment by Voclav** [comment]
![spotřeby](https://user-images.githubusercontent.com/23616018/89630093-2297e100-d89f-11ea-958c-70a0201388de.PNG)

Tohle nejsou spotřeby, které tam byly nastaveny při zakládání vozidel.

**Comment by Voclav** [comment]
Tak to asi nebude problém. Chyba je malá.
Původně jsem si myslel, že bude větší, ale bylo to tím, že jsem si spletl TP od dvou vozidel.

**Comment by Voclav** [comment]
I tak chce vedoucí střediska, aby se opravili spotřeby u těch vozidel, u kterých se budou vystavovat ceťáky, aby byly hodnoty v účetnictví správně.

**Comment by sinacek** [comment]
napiš mi ID nějaké cestáku, kde to je špatně a  kolik by tam mělo být správně podle tebe

**Comment by Voclav** [comment]
U sebe jsem to vyřešil tak, že jsem založil nový vozidlo. To starý jsem archivoval a u všech cesťáků jsem nastavil to nové. Spíš je blbý, že ta chyba bude u všech vozidel v celý organizaci.

**Comment by sinacek** [comment]
potřebuju vidět nějaky konkretní příklad co je špatně

**Comment by Voclav** [comment]
Tady v tom kometu je to vidět [https://github.com/skaut/Skautske-hospodareni/issues/1444#issuecomment-670419707](url). Ty spotřeby se asi při nějaké změně v databázi trochu posunuly. Sice tak málo, že výsledná částka na cesťáku vyjde stejně, ale ty spotřeby se tam uvádějí a v účetnictví pak je jiná spotřeba než v technickém průkazu.

**Comment by novas108** [comment]
sorry že vám do tho vstupuji; ale chyba je v tom že někde přetypováváte float (32 bit) na double (64 bit) (datové typy desetinných čísel) z programátorského hlediska je to naprosto korektní (=nevyhazuje chyby). Jádro problému je v tom, že 0.1 v počítači má periodický rozvoj a zaokrouhlujete  (v případě float ukládáte ~0.100000001490116119384765625... místo 0.1) (=desetinná čísla v dekadické zápise nemůžete vždy přesně zapsat). Pokud zvýšíte někdy dále v kódu přesnost takto uloženého čísla (např. zde float->double), doplní se volná místa nulami a najednou vznikne chyba, které se už nezbavíte. Závěr: nekombinujte float & double a prosím opravte tu chybu.

**Comment by novas108** [comment]
problém je v tom, že jste dříve používali pro ukládání spotřeb datový typ float a ne double a při update se to nepošéfilo nějakým zaokrouhlením, nebo podobnou ptákovinou a vznikly zaokrouhlovací chyby.

**Comment by sinacek** [comment]
Opravil jsem záznamy v databázi zaokrouhlením na 2 desetinná místa, takže by to mělo být už ok

**Comment by Voclav** [comment]
Skoro všude se to zobrazuje dobře kromě tabulky na stránce https://h.skauting.cz/cestaky/vozidla. A bohužel tam, kde je to nejdůležitější, tedy při vygenerování cesťáku v pdf se to zobrazuje pořád špatně, ale je možné, že je to někde nacachované.

**Comment by sinacek** [comment]
@Voclav Opraveno. Tam jsem to zapomněl zaokouhlit, tak jsem to nechal na 3 desetinna mista.
