### ISSUE TITLE
Vratky účastnických poplatků

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#1463]
Ahoj,
procházela jsem vratky u táborů a objevují se tyto problémy:

- vratka účastnického poplatku - dítě se z výnosů odečítá pouze, když je zadáno přes pokladnu, nikoliv přes banku. Je potřeba odečítat z položky Výnosy Od dětí a roverů bez ohledu na to, zda se vrátí hotově, nebo převodem. Obdobně by mělo fungovat u vratky dospělému s tím, že to bude odečteno z položky "Od dospělých".
- vratka u dospělého mi nelze zadat do pokladní knihy, ani banky - v horní části se zobrazuje "Nepodařilo se upravit záznamy ve skautisu."
Zkouším to tady (Tábor na faře):
https://h.skauting.cz/tabory/9975/kniha
- na kartě "Základní údaje" se mi zobrazuje Výsledek hospodaření bez zohlednění vratek (nicméně na kartě "Rozpočet" se to ve "Skutečných výnosech" počítá správně.

**Comment by sinacek** [comment]
Vratka dospělého - předpokládám, že tam nemáš příjmy od dospělých a skautis nepovolí záporný výsledek kategorie. Tohle upravím aby to vypsalo lepší hlášku

**Comment by sinacek** [comment]
Rozdíl mezi vracením přes banku a přes pokladnu se mi nepodařilo nasimulovat. Nasadil bych opravu a pokud chyba bude přetrvávat, tak znovu otevreme issue.

**Comment by manulekonecna** [comment]
Tak jsem to teď zkoušela a už se to odečítá správně. Ještě dole na stránce u evidence plateb https://h.skauting.cz/tabory/9975/kniha se zobrazuje výsledek hospodaření, kde vratky nejsou zohledněny. 
![image](https://user-images.githubusercontent.com/37432874/94250474-8f376f80-ff21-11ea-8765-7432da895973.png)

**Comment by sinacek** [comment]
ale ta oprava není ještě nasazená. Opravuju to hlavně v Zaverecne zprave akce
