### ISSUE TITLE
Nejde přidat email jako oddílový vedoucí

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1510]
Narazil jsem na chybu, nově přes Google O-Auth se dají přidávat emaily pouze jako vedoucí/admin střediska a hospodář střediska. Nemůžu přidat email jako vedoucí/admin oddílu a to je podle mě chyba. 

Když se v popisu píše "Nově připojený účet bude přiřazen jednotce dle aktuálně užívané role." potřebuju aby emaily jednotek byly přiřazené k jednotce kam patří. A né pod středisko.

![image](https://user-images.githubusercontent.com/8988898/99692597-c5f5b600-2a8a-11eb-85ad-a44d5214ff60.png)

**Comment by fmasa** [comment]
> Nově připojený účet bude přiřazen jednotce dle aktuálně užívané role.

Ta logika je určitě chybná. Mělo by se přiřazovat jednotce s ID v URL, tohle se chová jinak než zbytek systému.

> Nemůžu přidat email jako vedoucí/admin oddílu a to je podle mě chyba.

Tohle máš ověřené? Při pohledu do kódu vidím, že se bere ID jednotky z aktuální role, tzn. pro oddílovou roli by to mělo být ID oddílu.

**Comment by kalich5** [comment]
> Nově připojený účet bude přiřazen jednotce dle aktuálně užívané role.
> 
> Ta logika je určitě chybná. Mělo by se přiřazovat jednotce s ID v URL, tohle se chová jinak než zbytek systému.

No prostě to nefunguje, viz obrázek nahoře. Mám tam roli vedoucí/admin oddílu a nic nemůžu přidat. 

> Nemůžu přidat email jako vedoucí/admin oddílu a to je podle mě chyba.

> Tohle máš ověřené? Při pohledu do kódu vidím, že se bere ID jednotky z aktuální role, tzn. pro oddílovou roli by to mělo být ID oddílu.

Ano mám to ověřené, nefunguje to

**Comment by sinacek** [comment]
<img width="1127" alt="Screenshot 2021-01-03 at 12 14 59" src="https://user-images.githubusercontent.com/1140123/103477253-5bd86c80-4dbd-11eb-84a7-b75849d260fa.png">

Mě se to vpohodě zobrazuje. @kalich5 zkontroluj si, že nemáš v URL uvedené ID tvého střediska místo oddílu

**Comment by kalich5** [comment]
No to je tím, že se při změně role nenačte stránka znovu. Prostě se změní role, ale URL se nezmění. To není úplně intuitivní chování.

**Comment by sinacek** [comment]
To je správně. Pokud příjdeš na stránku, kde nemáš oprávnění a pak si změníš roli, tak už se ti zobrazí. Takle je to i ve skautisu.

**Comment by kalich5** [comment]
To jo, ale pokud jsem na stránce a přidávám emaily pro různé jednotky. Přidám jeden email, změním roli a musím vyskovat až kdo ví kam aby se to načetlo správně.
