### ISSUE TITLE
Skupina plateb "Registrace"

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1519]
Při přidávání plateb na h.skauting.cz (skupina plateb "Registrace") se mi v nabídce zobrazí pouze omezený 50 lidí a nejsem upozorněn, že ten seznam není úplný. Zprvu mě to zmátlo, ale zbylé osoby se zobrazí až poté, co nějaké přidám. Jinými slovy, pokud máte hodně lidí, nejdou přidat platby všem v jednom kroku. Nicméně to je matoucí a chtělo by to nějak opravit.

Tohle přišlo na SkautIS účet na FB.

**Comment by fmasa** [comment]
Ta informace tam je, maximálně ji můžeme zvýraznit.
![image](https://user-images.githubusercontent.com/5658260/100901445-1a098d00-34c4-11eb-8699-42984dba14ef.png)

**Comment by kalich5** [comment]
Jako a nešlo by tam přidat tlačítko, zobrazit všechny členy. Aby to pak nemuseli lidi přidávat ručně... To by podle mě dost pomohlo.

**Comment by sinacek** [comment]
Zobrazit všechny nelze, protože pak ten formulář má příliš mnoho prvků, což je hodně dotazů na skautis a hodně html formulářových políček, coz pak vedlo, že se jich odeslalo asi jen 1000.

**Comment by kalich5** [comment]
A zvýšit to na 100? Jako třeba u mě by byl problém u všech oddílů. Máme tra 60 lidí, a to zvýšení by mohlo hodně pomoct.

**Comment by sinacek** [comment]
jakmile jich 50 přidáš, tak pak už ti to příště zobrazí jen zbylých 10. To číslo 50 vyšlo zkušeností s tím, co se daří zobrazovat.
