### ISSUE TITLE
Vybírání členů do registrace na základě oddílů

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#1576]
Ve zkratce jde o to, že když přidávám členy do registrace (jako do plateb) a jsem tam s rolí správce střediska, akcí atd..., tak vidím všechny členy ze všech oddílů. Je tudíž velmi těžké přidat jen lidi za jeden oddíl. Když vezmu v potaz, že vidím jen 50 lidí, tak je to o to těžší. Ano, lze si vzít roli jen takovou, kde mi to ukáže můj oddíl, ale co když nejsem v žádném oddíle, ale jen vyřizuji registrace, nebo vytvářím platby za jiný oddíl?

Řešením by bylo nějaké drop down menu, kde bych mohl vybrat z oddíl střediska a zobrazilo mi to pak jen lidi v oddíle.

Díky,
Čaj

**Comment by fmasa** [comment]
Ahoj @Fradd747,
můžeš to prosím rozvést? U skupiny plateb typu *Registrace* lze hromadně přidávat členy dvěma způsoby:
- z jednotky (možnost "za člena") - tam dropdown pro výběr jednotky je 
![image](https://user-images.githubusercontent.com/5658260/104132257-5d390480-537c-11eb-9c8d-87b9a2c534b2.png)
- z registrace (možnost "za registraci") - tam dropdown není, ale jsou zobrazeni pouze členové ze související registrace (ta platební skupina je navázána na konkrétní registraci, která je vždy vázaná na konkrétní jednotku), takže pokud založíš skupinu pro registrace oddílu **A**, tak tam nemůžeš vidět členy z oddílu **B**. 

---

![image](https://user-images.githubusercontent.com/5658260/104132244-3e3a7280-537c-11eb-804b-d9350caff483.png)

**Comment by Fradd747** [comment]
Ahoj @fmasa .
jak rozdělím, jaká registrace je za jaký oddíl?

**Comment by Fradd747** [comment]
Máš na mysli tohle? 
![image](https://user-images.githubusercontent.com/43049427/104136052-12c38200-5394-11eb-96da-ced1ec7188f6.png)
Tak toho jsem si předtím vůbec nevšiml. Každopádně nemám práva na to to změnit :D

**Comment by fmasa** [comment]
Ne, posílal jsem i screenshot. Přímo na té stránce pro výběr osob pro import. 

> Ahoj @fmasa .
jak rozdělím, jaká registrace je za jaký oddíl?

Momentálně se automaticky bere podle role při vytváření platební skupiny.
@sinacek Tady by dávalo smysl přidat mezikrok podobný tomu u akcí a táborů, co myslíš? Dát možnost vybrat pro jakou jednotku registraci dělám.

@Fradd747 V tu chvíli by to bylo dostatečné řešení? Pak by bylo možné přidat jednoduše platby všech registrovaných osob z registrace daného oddílu/střediska.

**Comment by Fradd747** [comment]
Jasně, děkuji. Neměl jsem dostatečná práva.

**Comment by sinacek** [comment]
> Tady by dávalo smysl přidat mezikrok podobný tomu u akcí a táborů, co myslíš? Dát možnost vybrat pro jakou jednotku registraci dělám.

Možnost to je, ale budeme to muset realizovat jako X dotazů na skautis, kde X počet podjednotek +1 za středisko. Pokud to chceme, tak bych udělal nové issue a tady to uzavřel
