### ISSUE TITLE
Registrace plateb - vyhodnocení částky k platbě, pokud je osoba členem u více oddílů

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#1578]
### Popiš chybu
Pokud je osoba zaregistrována u více oddílů jedné organizační jednotky - u některého oddílu jako host, tak se v Platbách generuje hodnota 0 Kč.

### Jak chybu nasimulovat
Generování platby, kde je osoba řádně registrovaným členem a zároveň hostem.

### Očekávané chování
Prosím o takovou úpravu, aby se vygeneroval součet částek - tj. pokud je někdo hostem za  100 Kč a zároveň registrovaným členem za 1500 Kč, bude v platbě zobrazena částka k úhradě 1600 Kč.

### Snímky obrazovky
Pokud máš, přidej snímek obrazovky.
![obrazek](https://user-images.githubusercontent.com/37432874/105844098-f43ac900-5fd8-11eb-8c58-4f1b9101d170.png)

### Uživatelské informace:
 - Sekce: Platby
 - Uživatelská role: vedoucí/admin střediska 119.67 
 - Platby Registrace 2021 https://h.skauting.cz/platby/1122

**Comment by kalich5** [comment]
No to nevím jestli je dobře, protože každá ta částka určitě půjde na jiný účet.

**Comment by manulekonecna** [comment]
@kalich5 Jedná se o jednu organizační jednotku - ještě doplním do zadání upřesnění. Tedy mělo by to jít na 1 účet jednotky. Díky.

**Comment by manulekonecna** [comment]
Ještě mě napadla varianta, že by se tam mohly 1. generovat všechny platby - tedy nesčítat, ale bylo by to tam 2x a 2. negenerovaly by se platby s výší 0 Kč.

**Comment by kalich5** [comment]
@manulekonecna pokud je to v jedné jednotce, pak nějak nechápu proč se řeší hostování a ještě platba za něj...

**Comment by manulekonecna** [comment]
Kalichu, máme u nás na středisku oddíl roverů a ti roveři jsou aktivní v jiných oddílech - ve vedení, takže tam potřebují být zaregistrovaní. Zároveň chtějí být členy tohoto roverského kmene -tam tedy hostují. A u plateb se nám pak nyní generuje 0 Kč.

**Comment by fmasa** [comment]
@manulekonecna 

> Prosím o takovou úpravu, aby se vygeneroval součet částek - tj. pokud je někdo hostem za 100 Kč a zároveň registrovaným členem za 1500 Kč, bude v platbě zobrazena částka k úhradě 1600 Kč.

Varianta, kdy je nějaký člen registrovaný vícekrát ve stejné jednotce a odvádí více částek mi přijde jako rarita (pokud někdo takový vůbec je).

> Ještě mě napadla varianta, že by se tam mohly 1. generovat všechny platby - tedy nesčítat, ale bylo by to tam 2x a 2. negenerovaly by se platby s výší 0 Kč.

Tohle mi dává smysl. Prostě registrované osoby s částkou 0 Kč v tom výpisu nezobrazovat.

**Comment by fmasa** [comment]
@manulekonecna Jinak OT, ale tím, že je tento repozitář veřejný, tak bych sem neposílal skutečná jména + emaily členů, případně  bych je alespoň překryl (uvedu to i do issue template) :slightly_smiling_face:

**Comment by manulekonecna** [comment]
@fmasa Díky, upravila jsem, aby nebyly vidět členové.

Zároveň souhlasím s variantou, že registrované osoby s částkou 0 Kč se nebudou ve výpisu zobrazovat.

Díky
