### ISSUE TITLE
Nette 3.0

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1607]
- [ ] přejít na DateTime picker https://componette.org/radekdostal/nette-datetimepicker/ - má verzi pro Nette 2.4 i 3.0

Navazuje #1341

**Comment by fmasa** [comment]
@sinacek Tohle můžeme zavřít, ne?

**Comment by sinacek** [comment]
je tam ten datepicker, který jsme chtěli změnit

**Comment by fmasa** [comment]
Zahodil jsem při té migraci ten původní a přidal vlastní implementaci.
Je to jedna třída, tak bych radši osobně měl vlastní v aplikaci než sáhnul po knihovně, kterou někdo po roce zas opustí, jak je zvykem u většiny Nette extensions 😄
