### ISSUE TITLE
Duplikovane Variabilni symboly mezi paralelnimi Platebnimi skupinami

### ISSUE THREAD

**Issue by xoktj00** [skaut/Skautske-hospodareni#1657]
Pravdepodobne nizka priorita nebo mozna jen moje neschopnost. 

Ale nebylo by mozne vynutit unikatnost variabilnich symbolu vramci jednotky, tak aby jednotlive platby pokracovaly v zacate rade. 

V soucasnosti, kdyz vytvorim novou skupinu plateb, je defaultni start rady variabilnich symbolu stejny pro obe, a dogenerovanim vzniknou stejne variabilni symboly v obou, v mem pripade paralelnich, platebnich skupinach. 
Automaticke parovani plateb pak nefunguje spravne a uzavira platby, ktere bylo dokoncene pro jinou platebni skupinu.

**Comment by sinacek** [comment]
Kontrola unikátnosti v rámci celé jednotky je složitá v tom, co se má stát, pokud neprojde, protože vedoucímu oddílu to odmítne něco založit nebo to přeskočí řadu na další a udělá to chaos. Nyní je doporuceno domluvit si ve středisku systém a podle něj VS skládat. 

Např: 
odddí (OO):
- vlčata 01
- skauti 02

a pak dle měsíce (MM) a pořadí akce (P) a XXXX pro jednotlivé platby, tedy  celkem `OOMMPXXXX` -> 

Dvanáctá platba na druhé výpravě skautů v květnu: 020520012

**Comment by fmasa** [comment]
@xoktj00 Případně hospodaření přímo pro každou skupinu předvyplňuje unikátní číselnou řadu. Takže pokud se vám nechce nastavovat nějaké vlastní schéma ve středisku, tak stačí ponechávat výchozí hodnotu při vytváření skupiny.

**Comment by xoktj00** [comment]
Děkuji moc za odpovědi, 
@sinacek diky moc za doporučení, příště si dám při zakládání platební skupiny pozor abych upravil "Další VS" na nějaký unikátní "začátek nové řady"

Musím říct že jsem očekával že jedna z následujících věcí bude fungovat jinak

- Při založení Platební skupiny bude "Další VS" automaticky unikátní (tak to podle mě popisuje @fmasa) ale není to tak. Zatím jsem založil tři skupiny, první byla registrace a prefix její řady se vygeneroval na "2100301". Nedávno jsem ale založil dvě skupiny na Tábor a "Další VS" prefix se u obou předvzplnil stejný na "2100303"
- Při použití tlačítka "Dogenerovat VS" jsem očekával, že se dogenerují unikátní VS napříč existujícími platebními skupinami, ale není tomu tak, oba tábory teď mají stejnou číselnou řadu VS.
- Nakonec KS. Pro každý tábor jsem zvolil unikátní KS, nicméně při automatickém párování plateb se KS nespároval.

Tudíž ve výsledku se mi při automatickém párování plateb v táboru A započítaly i platby za tábor B, které mají stejný VS, i přes to že mají jiný KS. 

PS: Není to za mě nijak kritické, a nějak si poradím, Jen jsem chtěl nějakou cestou dát feedback na funkcionalitu, která nefungovala tak jak bych si představoval 0:)
PPS: Omlouvám se že jsem svůj případ nepopsal pořádně už od začátku.

**Comment by sinacek** [comment]
>     * Při založení Platební skupiny bude "Další VS" automaticky unikátní (tak to podle mě popisuje @fmasa) ale není to tak. Zatím jsem založil tři skupiny, první byla registrace a prefix její řady se vygeneroval na "2100301". Nedávno jsem ale založil dvě skupiny na Tábor a "Další VS" prefix se u obou předvzplnil stejný na "2100303"

Ty skupiny jsou na sobě nezávislé a pokud si to všude převyplníš stejně, tak ti to pak stejně generuje. Systém neví jak dlouhou řadu v kuse budeš potřebovat, proto není možné zachovat posloupnost a uníkátnost automaticky. 

>     * Při použití tlačítka "Dogenerovat VS" jsem očekával, že se dogenerují unikátní VS napříč existujícími platebními skupinami, ale není tomu tak, oba tábory teď mají stejnou číselnou řadu VS.

To se dogenerovává opět pouze pro danou skupinu. 

>     * Nakonec KS. Pro každý tábor jsem zvolil unikátní KS, nicméně při automatickém párování plateb se KS nespároval.

KS = konstantní symbol a ten slouží k finanční evidenci typu platby dle daných kritérií. Napříkad KS=340 značí reklamu a u všech plateb za reklamu bude konstantní a stejný. Pro párování se používá pouze VS + částka

**Comment by fmasa** [comment]
Zkusím prověřit ty neunikátní výchozí řady. Rozhodně by to mělo fungovat tak, že když nezměníš tu radu při vytváření skupin, ale ponecháš výchozí, tak se do tohoto problému nedostaneš.
Tak může někde být bug.

**Comment by xoktj00** [comment]
Jasne dekuji vam obema. 
Nase stredisko ma prave v hospodareni predpis na KS misto na VS 
{cislo oddilu}{rok}{konkretni cislo pro typ platby registrace} ... (meli jsme i originalne 5ti mistne KS} ... nas problem 😅
