### ISSUE TITLE
Po úpravě detailu platby se nepřekreslí tabulka

### ISSUE THREAD

**Issue by vojta001** [skaut/Skautske-hospodareni#1660]
### Popiš chybu

Po úpravě detailu platby se nepřekreslí tabulka, resp. překreslí se před aplikováním změn. Pokud např. procházím přes položky odshora dolů a upravuju je, úpravy vidím o 1 krok zpožděné.

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci 'Platby'
1. Vytvoř platební skupinu
1. Vytvoř několik nových plateb
1. Klikni na 'Upravit platbu'
1. Uprav VS
1. Ulož úpravu
1. Sleduj tabulku

### Očekávané chování
Překreslená tabulka po uložení bude obsahovat nová data.

### Uživatelské informace:
 - Sekce: (příklad: Platby/Platební skupiny)
 - Uživatelská role: vedoucí/admin střediska

Nevím, zda-li je to relevantní, ale dopisoval jsem variabilní symboly osobám, které žádný přiřazený neměly.

**Comment by vojta001** [comment]
Update: upravoval jsem ještě jinou platební skupinu a tam to fungovalo v pořádku. Tak nevím, jestli se mi třeba nenačetl nějaký JS, nebo na čem to závisí.

**Comment by sinacek** [comment]
Tedka jsem to zkoušel a chybu se mi nepodařilo nasimulovat.
