### ISSUE TITLE
Editovatelná poznámka u každé platby

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1672]
Ellie - občas se nám stává, že platby párujeme ručně, šlo by mít u platby nějakou vlastní poznámku? typu jako chybný VS, chybělo VS, ... takový záznam nejen kdo a kdy to ručně spároval ale proč

**Comment by fmasa** [comment]
U plateb poznámky jsou. Jen nejdou upravovat po spárování

**Comment by sinacek** [comment]
Přidat skrytí sloupců https://contributte.org/packages/contributte/datagrid/columns.html#column-status
- skrýt defaultně KS
- přidat sloupec Poznámka (skrytý)
- přidat ikonu do akcí s po najetí poznámku
