### ISSUE TITLE
Nefungují VRATKY

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1674]
https://h.skauting.cz/platby/1160/repayment

Vratky
500
Server Error
Omlouváme se, ale nastala neočekávaná chyba a server není schopen dokončit požadavek. Chyba byla uložena, zkuste tedy požadavek opakovat později.

Skautské hospodaření

**Comment by fmasa** [comment]
Sentry event: https://sentry.io/organizations/skautske-hospodareni-of/issues/2453744621/?project=1328535

Mrknu na to. Jinak příště prosím použij tu existující issue šablonu.
