### ISSUE TITLE
Bankovní účty - deformovaná tabulka

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1690]
### Nějak se deformovala tabulka
https://h.skauting.cz/platby/65/bankovni-ucty/detail

![image](https://user-images.githubusercontent.com/8988898/124568992-d4d87f80-de45-11eb-8807-c9b3db6d9672.png)

**Comment by fmasa** [comment]
@kalich5 můžeš poslat víc informací? Minimálně prohlížeč + rozlišení. Mně (FF, 1920x1080) se zobrazuje správně.

**Comment by kalich5** [comment]
Já mám Chrome v poslední verzi a doma mám 2560x1600 a v práci 1920x1080 a na obou je stejný problém.

**Comment by fmasa** [comment]
Ověřil jsem i v Chrome a nepodařilo se mi reprodukovat. Zkus si zkontrolovat, jestli ti to nedělá nějaký doplněk.
