### ISSUE TITLE
V releasu chybí generování cache

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1712]
Na produkci bez debug mode se nezobrazovali stránky, protoze je chyba s nacitanim cache. Donahral jsem bin/console a pustil `./console  orm:generate-proxies` a pak uz je to ok. Nevim jestli staci pridat generovani cache do releasu nebo je potreba pridat bin/console. Kazdopadne bin/console by se hodil mit i v releasu.

**Comment by fmasa** [comment]
To generování proxy tříd už tam je, ale koukám, že jsem s přechodem na Contributte Console nepřehodil v deploymentu a volá se to přes `www/index.php`. Upravil jsem v https://github.com/skaut/Skautske-hospodareni/pull/1716
