### ISSUE TITLE
Upgrade na webpack 5

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#1814]
webpack 4 má security dependency issue na glob-parent

**Comment by fmasa** [comment]
A zasahuje nás nějak?

**Comment by sinacek** [comment]
> A zasahuje nás nějak?

To jsem nezkoumal, jen nam ho to hlasi v security issues tak jsem hledal proc to mame

**Comment by fmasa** [comment]
Tak jsem koukal a nezasahuje nás to. Ta CVE označuje potenciální DoS, což se nás netýká - je to součást build toolu nikoliv výsledného bundlu. I kdyby to bylo součástí bundlu, tak tím, že je to jen klientský JS, tak tam je attack vector IMO minimální.

**Comment by marekdedic** [comment]
Opraveno zde: #2171
