### ISSUE TITLE
Duplikování řádků na cestovních příkazech

### ISSUE THREAD

**Issue by bjeta** [skaut/Skautske-hospodareni#1821]
### Popiš tvůj návrh řešení
Pokud tvořím cestovní příkaz například na tábor, jednotlivé cesty se hodně schodují. Velmi by ulehčilo vytváření pokud by bylo možné cestu vytvořit jednou a buď řádek zduplikovat nebo zadat kolikrát se má započítat.

**Comment by fmasa** [comment]
@bjeta Duplikovat cesty v cesťácích je možné i v aktuální verzi:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5658260/150000322-4d2ece7a-ec6c-49de-b6a4-4542d94b52d0.gif)

---

Jinak prosím dodržuj ten předepsaný formát issue, který ti Github předvyplní. Usnadňuje to pak všem práci :slightly_smiling_face:

**Comment by bjeta** [comment]
Děkuji. Snažili jsme se na to přijít s dalšími uživateli a shodli se že to
nejde ale my to jen neuměli

Dne út 18. 1. 2022 19:52 uživatel František Maša ***@***.***>
napsal:
