### ISSUE TITLE
Rodinné platby

### ISSUE THREAD

**Issue by bjeta** [skaut/Skautske-hospodareni#1822]
### Popiš tvůj návrh řešení

Možnost groupování plateb

**Comment by sinacek** [comment]
Tohle není popis jak by se to mělo řešit. Když chceš udělat platbu za více osob, tak vždy jde založit ručně s libovolnou částkou

**Comment by fmasa** [comment]
Nebyl bych úplně tak příkrý :grinning: 

@bjeta Z toho, co popisuješ není moc jasné, o jaké groupování se jedná. Jedná se o možnost vytvoření např. registrace pro dva různé lidi v rámci jedné platby (typicky sourozenci ve stejném oddílu)?
Nebo se jedná o to, aby se nějak automaticky párovaly platby, které plátce z nějakého důvodu sloučil? Nebo něco úplně jiného?

Jak psal @sinacek, ta předvyplněná šablona v issue slouží právě proto, ať máme nějaký základ, na kterém můžeme diskutovat. Takhle máme jen spoustu otázek. :slightly_smiling_face:
