### ISSUE TITLE
Hospodář VzA nemá přístup k cesťáku založenému členem VzA

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#1851]
### Popis problému
S rolí "VzA: vedoucí" jsem otevřel h.skauting, šel nahoře v menu do sekce cesťáky, založil si cesťák na poradu VzA, vyplnil, uzavřel. Náš hospodář si ho chtěl stáhnou, ale nemá k němu přístup, ať už s rolí Hospodář VzA nebo VO v pořádající jednotce (VS nemá)

### Popiš tvůj návrh řešení

Nevím, jak tam přesně jsou řešené ty přístupy a pravidla, tak moc nevím, zda tam jde dát něco granulárnějšího než "Hospodář VzA vidí všechny cesťáky ve středisku"... 

Díky!

**Comment by sinacek** [comment]
Dohledal jsem si tvuj cesták do Pardubic na poradu, předpokládám, že o tom mluvíš. Ten je navázán na jednotku 534.03 a hospodář 534.03 by to měl vidět. Můžeš to zkusit s ním prověřit? Případně mi do mailu poslat podrobnější informace o kterém mluvíme cestáku apod.

**Comment by marekdedic** [comment]
Jo, jde o můj cesťák do Pardubic. Mně ale nejde o hospodáře jednotky (v tomhle případě středisko Javor), ale o hospodáře VzA pořádané tou jednotkou (Odyssea 2022, pořádaná Javorem) - to dost často jsou různí lidé a hospodář VzA nemá roli hospodáře střediska...

Jestli potřebuješ vědět, o koho přesně jde, tak to radši tím mailem :)

**Comment by sinacek** [comment]
Jo takle, ja jsem to stale hledal druhým směrem. Nyní si u cestáku pamatuju jen `unitId` a `ownerId`. Tedy nemám jak poznat, že se daný cesták řadí primárně k akci a ne k jednotce. Chápu ten use case, ale upřímně se mi kvůli pár vzdělávačkám nechce měnit systém oprávnění pro celou sekci.

**Comment by marekdedic** [comment]
Jo, to chápu. A řešení "člověk s rolí hospodáře VzA vidí všechny cesťáky jednotky"? Jakože uvidí pak i věci, co by nemusel, ale zas tak špatný mi to nepřijde...

**Comment by sinacek** [comment]
No to dokaže u některých lidí udělat velké vášně, když by nějaký externí hodspodář viděl data celého střediska.

**Comment by marekdedic** [comment]
Jakože já bych argumentoval tím, že to je hospodář akce, kterou (včetně hospodáře) schválila SRJ... :smile: Ale chápu, že tím nepřesvědčím každého...

**Comment by sinacek** [comment]
Hospodar akce to je, ale tim nema videt vsechny ostatni akce střediska
