### ISSUE TITLE
Při zakládání cesťáku není jasné, zda u cestujícího vyplnit telefon nebo E-mail

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#1852]
### Popiš chybu

Když vyplňuju cesťák, chce to po mně "Kontakt na cestujícího", ale v PDF exportu je to "Telefon".

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Založím nový cesťák
2. Dole pod "Cestující" je kolonka "Kontakt na cestujícícho"
3. Vyplním mail, protože to je přeci taky kontakt...
4. Dovyplním a uzavřu cesťák
5. Exportuju si PDFko a tam je "Telefon: test@email.test"

### Očekávané chování
Buď by při zakládání mělo být jasné, že tam mám vyplnit telefon, nebo to musí být celé nějak sofistikovanější, aby se to dalo odlišit.

### Snímky obrazovky

![Screenshot from 2022-02-28 19-22-05](https://user-images.githubusercontent.com/3134692/156042984-7a58142f-a44d-4fb3-bcbe-66042b9e23ac.png)

![Screenshot from 2022-02-28 19-22-39](https://user-images.githubusercontent.com/3134692/156043009-cfc7d840-1805-4fdc-932b-2e467ecf99be.png)

**Comment by sinacek** [comment]
Jen přejmenuji to položky v exportu, protože dříve se používal jen telefon, ale dneska už dává smysl použít obecně nějaký kontakt.

**Comment by marekdedic** [comment]
Dává smysl, díky!
