### ISSUE TITLE
E-mail je špatně, není tam pomlčka

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#1908]
Všude, kde se používá slovo email je psané takhle blbě! V celém h.skautingu by to mělo být takhle: e-mail i podle správného pravopisu.
https://www.pravopisne.cz/2015/01/e-mail-x-email/

Jsou to sekce platby, platební skupiny, e-maily, a další. Prosím koukněte na to a upravte systém tak aby byl v souladu s pravopisem. Dík

**Comment by sinacek** [comment]
Proč nepošleš rovnou MR kde to bude upravene? tohle neni technicky náročné

**Comment by kalich5** [comment]
Protože nevím, kde ty části jsou uložené. Vy to budete mít opravené za chvíli.
