### ISSUE TITLE
Přidání sekce pro vzdělávací akce

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#192]
Ve skautisu je nový typ akce a to vzdělávací akce. Zatím zde nemáme pro ně podporu, ale stálo by za to zjistit jestli mají stejné potřeby jako akce nebo tábory a jen to zkopírovat do nové sekce.

**Comment by sinacek** [comment]
Ptala se na to Ellie s okres Brno město. Zajímá jí to aby měla vše na jedné platformě a mohla posílat platby. Je potřeba dořešit jak je to s akcema co běží přes více kalendářních roků a jak s počtem dnů u účastníků.

**Comment by manulekonecna** [comment]
V poslední době se mě na to ptali další zájemci, možná by bylo fajn toto ještě probrat s Mývalem.

**Comment by sinacek** [comment]
Znovu jsem se na to koukal a bude to složitejší než se to na prnví pohled zdá, vztáhnu to k uspořádání jako je u tábora. Zde moje pracovní poznámky.

## obecné informace
- není moc potřeba, asi stačí základní informace a pár statistik - jednoduché ale nic to neřeší

## účastníci
- jsou členěni v rámci akci na více kurzů (ČK vs VK)
- několik speciálních atributů - podmínky, náhradník, přijat, den absolvence -> ty bych u nás neřešil a pouze zobrazoval účastnický poplatek jako u tábora
- mají mít vratky a platbu na účet jako mají táborníci? 

## pokladní kniha
- potřeba rozdělit podle let konání akce - akce se může dělit na více let
- zde je přidaná hodnota, že se budou evidovat doklady jako u jiných typů akcí

## rozpočet
- potřeba rozdělit podle let konání akce - akce se může dělit na více let
- potřeba vyřešit jak se aktualizuje/neaktualizuje položka "Dotace"
- přidaná hodnota je pokud se to vyplní jako agregace dokladů

## (bankovní) platby
- není jasné které účastníky (náhradníky?přijaté?), kterého kurzu nabízet
- přidaná hodnota je protože jinak je komunikace s jednotlivky náročná
- jednoduše to propaguje použití h.skautingu
- je důležité dělat až kdyz budou přidělené účastnické poplatky nebo lze využít výchozí částku pro většinu?

**Comment by marekdedic** [comment]
Čau, asi pro tohle mám use-case, hledáme, jak účtovat Ody22 :) Navíc jsem už VzA hospodáře dělal, tak trochu tuším, co bychom potřebovali :)

Přijde mi, že spousta věcí bude podobná jako u táborů a akcí.
- Členění účastníků dle akcí je asi dobrý bonus, ale kdyby tam byli všichni dohromady, tak je to v pohodě.
- Účastníky to samozřejmě musí tahat z akce a ne jednotky.
- Vratky potřebujeme, platby na účet taky
- Zobrazoval bych přijaté účastníky, ve chvíli, kdy vezmeš náhradníka, tak ho stejně v ISu označíš jako přijatého
- Nemám zkušenost s víceletými akcemi. Pokud by to bylo komplikovaný, navrhuji začít bez toho, pokryje to asi tak 95% akcí.

Nabízím nějaké (omezené) množství času, zjednodušilo by nám to práci dlouhodobě.

**Comment by sinacek** [comment]
Ahoj, platby jsou již implementované. Má pro tebe smysl i když by se udělala jen některá z částí? co by tě zajímalo nejvíc?

**Comment by marekdedic** [comment]
Na to PR jsem koukal, pokud to správně chápu, je to o tom, že na záložce platby je možné založit skupinu pro úč. poplatky VzA, že?

Mně by nejvíc zajímala evidence plateb a s tím spojené generování pokladní knihy. Tam by většina funkčnosti mohla být přímo přenositelná z táborů a obecných akcí, ne?

**Comment by sinacek** [comment]
V modulu plateb máš i to párování zaplacených, tedy tu evidenci. Napojení na účastníky a pokladní knihu jsou přesně ty body s otazníkem. Máš jednu nebo více pokladních knih u vzdělávací akce? Seznam účastníků má více různých stavů, které se u akcí a táborů neřešili, takže je to potřeba rozmyslet.

**Comment by marekdedic** [comment]
Jo, asi si nejsem jistý vaší "terminologií" - já si pod evidencí plateb představím, že tam dám, že jsem Sinuhetovi proplatil půl kila bůčku, co koupil na večeři, ne jenom párování úč. poplatků z účtu - to tam teď není, ne?

Ok, pokud máte zájem, asi jakožto vzdělavatel můžu v tomhle pomoct - říct, co by se nám hodilo, tuším i, jak to dělají jiné kurzy

1. Více pokladních knih můžeš mít, pokud je akce přes více roků. To se stává, ale jen u naprostého minima akcí. Za mě i kdyby to bylo prvotně implementované jen pro akce v jednom roce, tak je to hodně muziky, představuju si že za relativně málo peněz.
2. Ok, co je tu k rozmyšlení? Já vidím:
    - Co s více kurzy: Za mě nacpat je všechny do jednoho seznamu je dostačující, mít je hezky přehledně podle kurzů je fajn, ale může být doplněno později
    - Naplnění podmínek neřešíme, to se řeší až v průběhu kurzu
    - Přijatí a náhradníci: Opět, mít tam i náhradníky a mít je nějak označené by bylo super, ale v první iteraci mi stačí přijatí - jakmile náhradníka vezmu (a tím pádem od něj budu chtít platbu), tak ho v ISu označuji jako přijatého (tedy `IsAccepted: true`).
    - Ale pro evidenci plateb (myšleno i příklad s bůčkem) seznam účastníků nepotřebuji, ne?

**Comment by marekdedic** [comment]
Související issues: (a často u nich jsou rovnou i PR):

- #2310
- #2311 
- #2313
- #2314 
- #2315 
- #2316 
- #2317 
- #2318
- #2319
- #2320
- #2322

Snažím se trochu ty vzdělávačky dotáhnout, abychom je příští rok mohli na kurzu použít, kdybyste měli ještě nějaké (konkrétní!) věci, co mi tam chybí, tak dejte vědět...

**Comment by marekdedic** [comment]
Zůstává podpora pro vzdělávačky pořádané v několika kalendářních letech a nějaké drobné nice-to-haves, ale jinak jsou podle mě vzdělávačky funkční a použitelné.
