### ISSUE TITLE
Dynamické odkazy v poznámce a přidání do QR kódu

### ISSUE THREAD

**Issue by Korbaja19** [skaut/Skautske-hospodareni#1930]
Mám dva podněty:

1) Aktuálně lze přidat ke každému účastníkovi poznámku, avšak nelze do ní napsat dynamický odkaz jako %name%. Vypíše se pouze string. Viz img.

![Screenshot_20220504-150555](https://user-images.githubusercontent.com/93582191/166688700-7cf75b5e-a6be-44c3-92fb-29cd814280e0.png)

2. Přidat propisování poznámky do QR kódu platby.

**Comment by sinacek** [comment]
Add 1) to bys vkládat dynamický obsah do dynamického obsahu, což je technicky možné, ale nevidím na to užitečný případ. Dneska lze vložit `Poznámka k platbě - %note% (%name%)` a tím získat jejich kombinaci

Add 2) do QR kodu se předává název platby. Pokud by si měl uživatel ještě konfigurovat, co chce předávat do QR kodu, tak by se to zbytečně komplikovalo
