### ISSUE TITLE
Výpis dokladů mimo grid

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#1986]
Výpis dokladů vyskakuje mimo grid stránky. Otevřel jsem hskauting i na telefonu i na jiném pc a stejně je mimo. Lze to opravit pomocí  table { table-layout: fixed; } a pak dodatečně přidat na checkbox u záznamu a jeho tlačítka .dependent-checkbox { white-space: normal; }.

![185804721-44b0c528-8b45-4a53-bee5-9e166e1e68b2](https://user-images.githubusercontent.com/43049427/202925741-daac390b-522b-4bce-bbd6-8c056c242607.png)

**Comment by sinacek** [comment]
duplicitní s https://github.com/skaut/Skautske-hospodareni/issues/1337
