### ISSUE TITLE
Není možné založit více jak jednu platební skupinu na registraci

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#2046]
Po vytvoření jedné platební skupiny typu registrace již není možné vytvořit další (například pro jiný oddíl). Po kliknutí na vytvořit se jen obnoví stránka. Velice by nám to ve středisku pomohlo. 

Vyzkoušel jsem role "středisko správce akcí" a "vedoucí/admin oddílu".

**Comment by sinacek** [comment]
pro kazdou jednotku má správně jít zalozit jen jedna skupina. Máš pro ostatní jednotky uz zalozene taky registrace?
