### ISSUE TITLE
Nelze zadat datum splatnosti na víkend

### ISSUE THREAD

**Issue by juradee** [skaut/Skautske-hospodareni#2047]
### Popiš chybu
Registrační skupina nelze založit s datem splatnosti o víkendu. Formulář nejde uložit, uživatel není nijak notifikován.

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci 'platby'
2. Klikni na 'nová registrace'
3. Pokusit se uložit registraci s datem splatnosti o víkendu
4. Nic se nestane

### Očekávané chování
a) Uživatel bude o této skutečnosti informován
b) datum splatnosti se posune na následující pracovní den

**Comment by sinacek** [comment]
idealni je posunout to, protoze on to sam nemuze zadat na vikend, ale tohle mu tam prednastavujeme my

**Comment by sinacek** [comment]
vyřešeno https://github.com/skaut/Skautske-hospodareni/pull/2048
