### ISSUE TITLE
Validace při přidání nové/odstranění položky na dokladu

### ISSUE THREAD

**Issue by TomasFurch** [skaut/Skautske-hospodareni#2105]
### Popiš chybu
V evidenci plateb u akce/táboru se při přidání/smazání položky na dokladu validuje správnost vyplnění všech údajů na dokladu.

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři evidenci plateb u akce
2. Klikni na 'Přidat další položku' 
3. Položka nejde přidat pokud není vyplněno datum dokladu nebo některý z povinných údajů na jiné položce

### Očekávané chování
Validace by měli probíhat pouze při ukládání dokladu.

### Snímky obrazovky
![Hskauting_odebrání_položky](https://user-images.githubusercontent.com/5067498/219503907-8c2ab2ce-df5d-40e8-8629-c9b54cf181fa.png)

**Comment by sinacek** [comment]
opraveno https://github.com/skaut/Skautske-hospodareni/pull/2219
