### ISSUE TITLE
Chybí ikony tlačítek

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#2188]
Úplně zmizela veškerá tlačítka z akcí u platebních dokladu. Zkoušel jsem na PC (chrome) i v anonymním režimu, i na telefonu a všude stejné.
![image](https://user-images.githubusercontent.com/43049427/233138657-f5476522-0f49-40b0-97ef-a30c880f85a2.png)

**Comment by sinacek** [comment]
problém je s Modal, protoze jsem to musel tady zakomentovat, jelikoz jsem nebyl schopen to jinak rozchodit https://github.com/skaut/Skautske-hospodareni/commit/02a4386db439dfde6c42217ee84052f1c141c46f#diff-52f14f75b05ffaaab72d8747a0a4b38722cd1b695b898e843fad7ad64f342339R28

**Comment by sinacek** [comment]
opraveno viz https://github.com/skaut/Skautske-hospodareni/issues/2191
