### ISSUE TITLE
Nelze exportovat výdajové doklady najednou

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#2191]
Nelze exportovat veškeré doklady najednou, pouze jednotlivě. Ani zaškrtávací tlačítko na vybrání dokladů nereaguje.
![image](https://user-images.githubusercontent.com/43049427/234627682-f81bb44a-2c11-4e90-874c-1f6e22531ff9.png)

**Comment by sinacek** [comment]
opraveno revertnutím update pro bootstrap 3
