### ISSUE TITLE
Zdvojený výběr typu dokladu

### ISSUE THREAD

**Issue by Fradd747** [skaut/Skautske-hospodareni#2192]
Při vytváření nového dokladu se zobrazují jak typy dokladů pro výdaje, tak typy dokladů pro příjmy viz img.
![image](https://user-images.githubusercontent.com/43049427/234652425-8bfbed61-a3bc-435d-a79b-ca4a06b60d53.png)

**Comment by sinacek** [comment]
souvisí s https://github.com/skaut/Skautske-hospodareni/issues/2191
