### ISSUE TITLE
tábor - účastník, nakonec nejede, vydává se mu 100% vratka - nesoulad seznamu účastníků a evidence plateb

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2212]
### 

- výběr úp před akcí/táborem -> tedy dám osobu do seznamu -> zadám celkové vybrané peníze do sekce banka
- osoba ze zdr. důvodů nejede ani na 1 den -> dáváme 100% vratku 

jak upravit seznam/banku?
- v seznamu osob nejde zadat 0 dnů  - účastník se musí z akce smazat;
- pokud necháš původní úp v evidenci plateb - h.skauting ti píše chybovou hlášku, že je nesoulad mezi seznamem a zadanými úp (i když v bance máš zadané i vratky)

**Comment by sinacek** [comment]
Ideálně domluvit s @jerrysohn a @manulekonecna aby skautis povolil 0 dnů.

**Comment by juradee** [comment]
SkautIs povoluje 0 dnů.  Přes API i GUI se dá 0 dnů propsat. 

Otázka je, jestli by člověk, které na akci de facto nebyl, měl mít v isu propsanou účast ve svém profilu.

**Comment by sinacek** [comment]
> Otázka je, jestli by člověk, které na akci de facto nebyl, měl mít v isu propsanou účast ve svém profilu.

Kdyz to umoznuje skautis, tak nemá smysl to zde taky nepovolit.
