### ISSUE TITLE
Nefunguje aktualizace účastníka tábora

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#2215]
### Popiš chybu
Nefunguje aktualizace účastníka tábora protože SkautIS nejspíš změnil rozhraní a vrací chybu `ParticipantCamp_IsAcceptedCantBeNull`. 

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci účastník tábora
2. edituj účastníka

### Očekávané chování
Změna se uloží

### Uživatelské informace:
```
System.Web.Services.Protocols.SoapException: Chyba validace (ParticipantCamp_IsAcceptedCantBeNull)
  at JunakWebservice.Utils.Validate(SqlCommand cmd, String procedureValidate, Boolean log, Boolean addActionParameter, XmlDocument doc) in D:\a\1\s\JunakWebservice\Utils\Utils.cs:line 185
  at JunakWebservice.Events.Events.ParticipantCampUpdate(ParticipantCampAllOutput participantCamp) in D:\a\1\s\JunakWebservice\Events\Camp\ParticipantCampUpdate.cs:line 39
```

**Comment by sinacek** [comment]
@jerrysohn můžete to udělat zpětně kompatibilní?

**Comment by sinacek** [comment]
čeká na opravu skautisu viz https://skautit.slack.com/archives/C4SDWBK6F/p1687337294670119?thread_ts=1686641864.131799&cid=C4SDWBK6F

**Comment by sinacek** [comment]
Tak oprava byla asi dneska nasazena https://napoveda.skaut.cz/skautis/nove-verze/14-7-5 - poslední řádek

**Comment by juradee** [comment]
Pokud chci poslat do Isu počet dnů na táboře, musím parametr nastavit na `IsAccepted` `true`, jinak se daná změna do Isu nepropíše. Tzn, pokud používám epřihlášku a chci editovat počet dnů na táboře, musí být daná osoba označena jako přijatá.
Je to tak OK?

![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/f398694f-e247-42fd-848a-0aa113d8f6df)

![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/fd3d7255-c455-46a0-b05a-32e7cc946f50)

**Comment by sinacek** [comment]
Ten stav by sis mel načíst ze skautisu a zase ho nezmeneny poslat zpět. Abys nekoho tim neschvalil navíc

**Comment by juradee** [comment]
To jsem udělal. Problém je, že pokud je ten stav na `false`, změna (počet dnů na táboře) se nepropíše do Isu

**Comment by sinacek** [comment]
Tak u tech lidi musime zamezit editaci kdyz to nemá vliv :/ ale teda jen kdyz pouzivam přihlášky

**Comment by juradee** [comment]
SkautIs se chová tak, že pokud to není zatržené, hodnota dnů se neuloží (Což je za mě pěkně divné chování...). Pokud zatržení zruším, nastaví se 0. 

Asi by šlo přidat toggle na tuhle hodnotu pro e-přihlášky a pokud hodnotu nastavím na `true`, zpřístupnit i pole na úpravu dnů.

**Comment by sinacek** [comment]
Nevim jak casto se to realne pouzije, takze bych klidně zatím vypnul editaci uplne u tech s elektronickou prihlaskou a zároven neakceptovaní.  Kdyz zjistime, ze je potreba editovat neakceptovane i kdyz stejne nepujdou menit dny, tak bych to pak resil dál.

**Comment by juradee** [comment]
OK

**Comment by juradee** [comment]
Upravil jsem editaci jednotlivce Vypadá to následnovně
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/d98184df-9583-4b21-a433-cea65f000ebb)

Mass edit pouze neprovede aktualizaci hodnot `days` pro uživatele, kteří nejsou přihlášení. Je to tak OK?

**Comment by sinacek** [comment]
> Parametr se nekontroluje, pokud tábor nemá e-přihlášku

Tohle by mělo i vypsat hlášku, u koho se to neaktualizovalo a proč.

**Comment by juradee** [comment]
Pravda.

![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/def5878e-3b31-4030-906a-5ca94d5b3b58)
OK? použil jsem class `warning`

**Comment by sinacek** [comment]
V druhé větě ve warningu chyní asi `není`. Nebo to upravit na `Následující účastníci nemají potvrzenou elektronickou přihlášku: %X%, %Y%, %Z%.`
