### ISSUE TITLE
evidence plateb (akce) - možnost potvrzení částky dokladu enterem 

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2217]
### Popis chyby
při zadávání nového dokladu se uživatel dostane do políčka částka 
- pokud omylem po zadání částky dá klávesu enter -> 
- přidá mu to novou položku, nikoliv potvrdí doklad ->
- nová (nechtěná) položka nejde smazat hned, ->
- je nutné u nové položky zadat účel a částku ->
- poté až jde položka odebrat

naši hospodáři toto vnímají jako uživatelskou nepříjemnost, která lehce zdržuje

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci akce
2. Vytvoř nový nový doklad
3. Vyplňuj položky až se dostaneš k částce
4. místo kliknutí na tlačítko Uložit dej enter

### Očekávané chování
 Uvítali bychom aby klávesa ENTER sloužila na potvrzování položek nikoliv k vytvoření nové položky na dokladu; případně, aby šlo novou/prázdnou/nechtěnou položku hned smazat (i bez vyplněné částky, účelu

### Snímky obrazovky
![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/730c8535-105e-4c3e-948d-9a33c11b2f15)

### Uživatelské informace:
 - Sekce: Akce/ evidence plateb
 - Uživatelská role: střediskový hospodář (ale i hospodář oddílu, správce akce oddíl, středisko, vedoucí oddílu)
 - akce: _libovolná_

**Comment by sinacek** [comment]
Ta možnost odebrat tam byla a přestala fungovat, tak tady nasazujuju hot fix https://github.com/skaut/Skautske-hospodareni/pull/2219 Přesměrování entru na jinou akci tady nechám pro pozdejsi upravy

**Comment by sinacek** [comment]
tu druhé chování již má issue zde https://github.com/skaut/Skautske-hospodareni/issues/2000, tak zaviram jako duplicitní
