### ISSUE TITLE
archivace vozidla - > chybová hláška 403

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2218]
### Popis chyby
při užití možnosti archivovat vozidlo se občas objeví chybová hláška, nicméně z pohledu uživatele se příkaz provedl; **neděje se vždy**

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci Cesťáky
2. Klikni na sekci vozidla
3. Vyber vozidlo, které chceš archivovat
4. Rozklikni jeho detail
5. Klikni na tlačítko Archivovat

### Očekávané chování
Vozidlo je archivováno (nezobrazuje se ve výčtu), uživateli se po archivaci vypíše hláška vozidlo archivováno.

### Snímky obrazovky
_Bohužel nemáme_
_neděje se vždy, i po chybové hlášce  403 je archivace provedena_

### Uživatelské informace:
 - Sekce: Cesťáky/ vozidla/
 - Uživatelská role: střediskový hospodář (ale i jakýkoli jiný činovník střediska i bez vyšší fce)
 - _konkrétní url bohužel nemáme_

**Comment by sinacek** [comment]
@juradee máš to assignuté, ale nevim jestli na tom děláš

**Comment by ellie-RM** [comment]
myslím, že už se to neděje
