### ISSUE TITLE
Úprava počtu dnů u účastníka tábora s e-přihláškami vyvolá chybu 500

### ISSUE THREAD

**Issue by 1ukastesar** [skaut/Skautske-hospodareni#2276]
### Popiš chybu

Tábor s e-přihláškami má zřejmě ve skautisu nějaké informace navíc a při pokusu o úpravu počtu strávených dnů na táboře u jednoho účastníka vyvolá chybu 500.

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Proklikni se na tábor, který letos plně používá e-přihlášky
2. Přejdi do sekce 'Seznam účastníků'
3. Zvol editaci u libovolného účastníka
4. V poli 'Počet dní' změň na libovolnou jinou než stávající hodnotu
5. Klikni na 'Upravit'

### Očekávané chování
1. Úprava se provede
NEBO
2. Vyskočí na mě chybová hláška, že tuto skutečnost musím upravit ve skautISu.

### Snímky obrazovky
![image](https://github.com/skaut/Skautske-hospodareni/assets/16971100/33ebd91c-36cf-4850-aa62-5cf67ea9f4cd)
![image](https://github.com/skaut/Skautske-hospodareni/assets/16971100/ad3222ea-ed48-4526-8574-c65e47252cfc)
![image](https://github.com/skaut/Skautske-hospodareni/assets/16971100/a2b56d75-0815-4e4e-bf33-a64c0b525a32)
![image](https://github.com/skaut/Skautske-hospodareni/assets/16971100/8477f0e9-f13a-4bc2-b80d-ec418efb5493)

### Uživatelské informace:
 - Sekce: Tábory/účastníci
 - Uživatelská role: 623.21 - Středisko: správce akcí
 - Tábor: https://h.skauting.cz/tabory/14148

**Comment by sinacek** [comment]
Duplicitní s https://github.com/skaut/Skautske-hospodareni/issues/2215 ale od @jerrysohn nemám žádnou reakci už delší dobu.

**Comment by 1ukastesar** [comment]
> čeká na opravu skautisu viz https://skautit.slack.com/archives/C4SDWBK6F/p1687337294670119?thread_ts=1686641864.131799&cid=C4SDWBK6F

Na ten Slack nemám přístup, ale chápu správně, že byla ve SkautISu nějaká breaking change? Každopádně díky za Tvoji práci.

**Comment by sinacek** [comment]
Ano, skautis má BC break, kde je nutné poslat jestli je ucastnik prihlaseny i kdyz tu hodnotu nijak neupravuju. Abych ziskal co aktuálně má a mohl to poslat zpět, tak si musím stáhnout všechny účastníky, v nich najít toho konkretního a tu hodnotu poslat. Což je něco, co mi nedává smysl takto realizovat
