### ISSUE TITLE
Nejde založit nová smlouva pro cestovní příkaz

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#2306]
Vedoucí oddílů nemají v roli vedoucí/admin možnost zakládat nové smlouvy. To dřív šlo, prosím opravit ať to zase jde. Jako vedoucí/admin střediska to můžu dělat

### Jak chybu nasimulovat
Vybrat si roli jako vedoucí/admin oddílu, přejít do sekce Cesťáky a kliknout na Smlouvy. Vyhodí to hlášku...
Nemáš přístup ke smlouvám cestovních příkazů.

### Očekávané chování
Očekávám, že si vedoucí můžou smlouvy u oddílu dělat sami. Dřív to šlo

### Snímky obrazovky
![image](https://github.com/skaut/Skautske-hospodareni/assets/8988898/88efaa41-55e0-46bf-bd5e-27a3a350e815)

**Comment by sinacek** [comment]
Smlouva se uzavírá se strediskem, tedy to musi delat admin strediska

**Comment by kalich5** [comment]
To jo, ale u nás mají vedoucí táborů zmocnění k tomu, aby si smlouvy a věci okolo tábora dělali sami. Takže tohle je omezení, které nás prostě obětěžuje že to nejde.
