### ISSUE TITLE
Nejde vygenerovat export

### ISSUE THREAD

**Issue by juradee** [skaut/Skautske-hospodareni#2356]
V sekci platby nelze vygenerovat export. ručně vkládaných dat. Pokud jsou data ze skautIsu, export proběhne. 

![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/9f2bc581-a839-46b0-9328-9bca7f069795)

**Comment by sinacek** [comment]
zkusil jsem si zadat platbu rucne i tak mi to generuje export. Muzes zkusit na https://test-h.skauting.cz/platby/skupiny/26 pod rolí u jednotky 621.66

Takze musí být problém někde v datech a na to bych potreboval pridelit dočasně roli u jednotky, abych si to přímo vyzkoušel.

**Comment by juradee** [comment]
Zkusím to replikovat a případně se domluvím na náhledu / přidělení role
