### ISSUE TITLE
Vypsání výše dotace ve statistikách o vzdělávačce

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2359]
### Popis problému
Když dělám hospodaření vzdělávačky, tak jedna z věcí, kterou průběžně řeším je, kolik dostanu peněz na dotaci. To se odvíjí od osobodnů, tj. když mi účastník nepřijede na část kurzu, přicházím tím o část dotace. Tedy mě opakovaně zajímá, jak na tom s tou dotací jsem...

### Popiš tvůj návrh řešení
Do základní obrazovky VzA (viz #2303) bych přidal ještě info o
- Maximální možné výši dotace
- Reálné výši dotace s aktuálním počtem osobodnů

Případně ještě údaj o tom, kolik % příjmů tvoří dotace, protože tohle číslo nesmí přesáhnout tuším že 70% (z hlavy, ověřit)

**Comment by sinacek** [comment]
Jak se zpočte maximální výše dotace? počítají se do toho i instruktoři? u těch vzdělávacích akcí, kde má 2 kurzy, tak počítám instruktory 2x? :D Obecně mi tady přijdou osobodny trochu riskantní počítat, tak bych rád, až to máme vyjasněné jak to dělat s někým z ústředí nebo pokud by to nemohl pocitat uz rovnou skautis. @manulekonecna @ellie-RM @jerrysohn

**Comment by marekdedic** [comment]
Obě dvě ty částky jsou přesně určeny směrnicí, je to počet účastníkodnů x sazba podle typu akce. Ale tipoval bych, že to ve SkautIS API někde bude, protože se to vypisuje u dotací VzA.

**Comment by sinacek** [comment]
> Obě dvě ty částky jsou přesně určeny směrnicí, je to počet účastníkodnů x sazba podle typu akce. Ale tipoval bych, že to ve SkautIS API někde bude, protože se to vypisuje u dotací VzA.

Kdyz uděláš v testovacim skautisu vzdělávací akci a pridas me tam jako zastupce, tak kdyz tam uvidim ktera cisla potrebujes, tak klidne najdu ktere funkce je potřeba volat a nemusime si to vubec pocitat

**Comment by ellie-RM** [comment]
@sinacek výše dotace je jen na účastníky - různá výše dle typu akce -> viz [směrnice k dotacícm (28)](https://krizovatka.skaut.cz/spisovna/smernice/hospodareni-a-dotace/smernice-k-dotacim-organizacnich-jednotek/2023-04/predpis)

a ano dotaci počítá to skautIS, tam také zadáváš skutečnou účast účastníků

**Comment by marekdedic** [comment]
Zajímavé info:
- Stav dotace
- Podíl na nákladech (%)
- Maximální možná výše
- Reálná výše dotace
- Přeplatek/doplatek

Ad API - podle mě by mělo stačit, co je v `Grants->GrantDetail` ;)
