### ISSUE TITLE
Přepínač rolí nezobrazuje název vzdělavačky

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2363]
### Popis problému
Mám hodně rolí u vzdělávaček. Můj přepínač rolí v h.skautingu vypadá takhle:

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/b872e6a5-19ce-4305-af80-8edeb6fca060)

V tom se hrozně blbě orientuje - mně upřímně moc nezajímá, kdy se ta vzdělavačka konala ani kdo ji pořádal (to se dočtu v ISu), ale zajímá mě její název a ten tam není.

### Popiš tvůj návrh řešení

Minimálně bych tam přidal název té VzA. Dál asi podle toho, co dovolí SkautIS API, za mě by ideální bylo něco typu `ČLK Odyssea 2023 - vedoucí`), ale to podle mě IS neumožní...

### Prostor pro další poznámky, snímky obrazovky či alternativní řešení

Podle toho, že se to podobně zobrazuje i v ISu bych tipoval, že to není věc h.skautingu, ale v ISu kromě všech těch "zbytečných" informací vidím i název té VzA...

**Comment by sinacek** [comment]
Tady to zobrazujeme stejne jako ve skautisu ne? Tedy bych se spis ptal jestli to nemuzou změnit tam jestli je to smysluplné

**Comment by marekdedic** [comment]
No právě že ne, SkautIS je ještě ukecanější, což v tomhle případě znamená, že tam napíše i to jméno tý akce:

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/4059cae0-08de-4c55-bd39-a01781e996be)

Což je za mě zbytečně moc informací, ale asi lepší, než aby tam ta akce nebyla...

**Comment by marekdedic** [comment]
Ale pošlu tohle issue na podporu, jestli to nechtějí zkrátit..
