### ISSUE TITLE
Uzavření akce na VOJ

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2366]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.
V roli správce akce u VOJ nejde zadat vedoucí akce. Jsem registrovaná na svém středisku, založím akci pod VOJ (krajem) a chci se dát jako hospodář/vedoucí akce - ale ve výběru mi to moji osobu nenabízí. Bez výběru vedoucího akce nelze akci uzavřít.

### Popiš tvůj návrh řešení
Nejsem si jistá řešením kvůli právům. Spíše se ptám kdo by měl akce (např. vzdělávačky) pod VOJ zadávat, aby byl se svými právy schopný vybrat osoby ve vedení akce.

### Prostor pro další poznámky, snímky obrazovky či alternativní řešení
![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/ec64eb1b-2394-40bc-b023-30fefc7d6351)

![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/16175563-88c3-460b-8aee-fcdc398cb6a7)

**Comment by sinacek** [comment]
Pro správu VOJ bych doporučoval použit přímo skautis, protože z pohledu hospodaření je to edge case.

**Comment by sinacek** [comment]
vedení akce si zadáš taky ve skautisu

**Comment by ellie-RM** [comment]
> vedení akce si zadáš taky ve skautisu

v roli správce akce VOJ můžeš jen založit novou akci, nevidíš tam propojení (výběr akcí), kdo by tedy akci v h.skautingu musel zakládat aby propojení viděl?

**Comment by sinacek** [comment]
Vubec nechapu dotaz. Akce jako takova lze stejne zalozit ve skautisu jako v hospodareni a neni v tom rozdíl. Jen hospodaření asi některé veci okolo zalozeni u voj neumí

**Comment by ellie-RM** [comment]
> Vubec nechapu dotaz. Akce jako takova lze stejne zalozit ve skautisu jako v hospodareni a neni v tom rozdíl. Jen hospodaření asi některé veci okolo zalozeni u voj neumí

ok, 

uzavírám tedy tento dotaz, že to není nyní priorita a buď si to vedoucí kurzů, aby akci mohli uzavřít stáhnou pod svou jednotku, nebo akce zůstanou otevřené
