### ISSUE TITLE
Dokumentace, jak lokálně pustit testy

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2377]
### Popis problému

Chci děkat lokální vývoj, takže si chci pustit testy, než to pushnu do GH. A neumím to. A není to nikde zadokumentovaný. A celý je to pro jistotu v dockeru...

Můj současný postup pro pouštění testů:
1. Zazálohuj si `app/config/config.local.neon`
2. Překopíruj `app/config/config.ci.local.neon` přes `app/config/config.local.neon`
3. Připoj se do dokeru
4. Pusť `phing init`
5. Pusť `phing-tests-acceptace`
6. Obnov `app/config/config.local.neon`, abys mohl dál fungovat

### Popiš tvůj návrh řešení

Chtěl bych 1 command, který pustí testy a nerozbije mi při tom celou aplikaci

### Prostor pro další poznámky, snímky obrazovky či alternativní řešení

- Možná jsem jenom blbej a něco jsem přehlídnul...
- To samý bych chtěl pro statickou analýzu. Ale tam aspoň nemusím kopírovat ty konfiguráky...

**Comment by marekdedic** [comment]
Respektive našel jsem https://github.com/skaut/Skautske-hospodareni/blob/master/.docs/tipy-pro-testovani.md, ale to mi nefungovalo, tak jsem manuálně okopíroval to, co dělá CI...


```
❯ vendor/bin/codecept run tests/acceptance/CreateUnitCashbookCept.php
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

In WaitForDb.php line 26:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql-test failed: Name or service not known


In WaitForDb.php line 26:

  PDO::__construct(): php_network_getaddresses: getaddrinfo for mysql-test failed: Name or service not known


run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]
```

**Comment by juradee** [comment]
Testy  se připojují na jinou db. Tu je potřeba mít správně nastavenou a puštěnou v dockeru. Zde to vypadá, že db neběží.

**Comment by juradee** [comment]
Já se přimlouvám ještě za sjednocení CSFix a beautifier. Teď jsou to dvě různé věci a každá se musí pouštět zvlášť. Změny, které dělá beautifier by se mohli vykonávat zcela automaticky před pouštěním fixeru.

**Comment by marekdedic** [comment]
> Testy se připojují na jinou db. Tu je potřeba mít správně nastavenou a puštěnou v dockeru. Zde to vypadá, že db neběží.

Jo, ale ta se pustí jenom s tím jiným configem, ne?

**Comment by juradee** [comment]
Konfigurace db jsou ještě v
https://github.com/skaut/Skautske-hospodareni/blob/2b88979e5d7582ec0a4f4c6aafd1022e79723d17/tests/acceptance.suite.yml
a
https://github.com/skaut/Skautske-hospodareni/blob/2b88979e5d7582ec0a4f4c6aafd1022e79723d17/tests/integration.suite.yml

**Comment by marekdedic** [comment]
Díky :)

**Comment by juradee** [comment]
Viz #2396 

Testy jde nově spouštět mimo prostředí kontejneru pomocí make 
`make tests-all`
