### ISSUE TITLE
Při lokálním vývoji chybí složka `temp/sessions`

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2380]
### Popiš chybu

Po spuštění (`docker-compose up -d`) dostávám tuhle chybu:

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/28623fde-9766-4948-a0c2-6391a8c98b6b)

A opravdu tam není:
```bash
www-data@d72f535cac88:~/html$ ls -l temp
total 8
drwxr-xr-x 8 www-data www-data 4096 Oct 12 13:13 cache
-rw-r--r-- 1 www-data www-data   23 Oct 12 13:22 tracy-50f9a084a3
```

Když ji ručně vytvořím, tak vše funguje, dokud nerestartuju docker-compose

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. `docker-compose up -d`
2. Otevři `moje-hospodareni.cz`

### Očekávané chování
Žádná chyba

**Comment by juradee** [comment]
Viz #2396 
Chyba oprávnění odstraněna sjednocením vlastníka souborů a procesů
