### ISSUE TITLE
Seznam umístění VzA obsahuje i umístění, která nejsou použitá

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2382]
### Popiš chybu

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/4af5aaaa-7e11-45da-8d51-2dd754304946)

Když jsem zakládal hlášenku akce, tak jsem jako umístění vyplnil Česko, protože jsem ještě nevěděl, kde budeme. Později jsem ke 3 termínům přidal umístění, ale v systému to "Česko" pořád existuje a nejde ho smazat (SkautIS má divně propojené termíny a umístění a tohle se může stát). Ale je to divný, protože to umśitění není v tom kurzu použité...

### Očekávané chování
Zobrazují se pouze místa, kde je nějaký termín kurzu

### Uživatelské informace:
 - Sekce: VzA

**Comment by sinacek** [comment]
Pokud se to stejne zobrazuje ve skautisu, tak to neni chyba hospodaření

**Comment by marekdedic** [comment]
Ve SkautISu je to vyfiltrované a "Česko" tam není
