### ISSUE TITLE
V dockeru nefunguje yarn

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2386]
### Popiš chybu

Když v dockeru (Připojen pomocí `docker/ssh`) pustím `phing init`, tak to nenajde `yarn`:

```sh
www-data@520193c51d18:~/html$ phing init
Buildfile: /var/www/html/build.xml

Skautske hospodareni > init:

     [copy] config.sample.local.neon omitted, is up to date
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
91 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
sh: 1: yarn: not found
sh: 1: yarn: not found

 WARNING! You are about to execute a migration in database "hskauting" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

 [OK] Already at the latest version ("Migrations\Version20231008115940")
```

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. `docker-compose up -d`
2. `docker/ssh`
3. `phing init`

### Očekávané chování
Nainstalují se yarn dependence

**Comment by sinacek** [comment]
ja si instaluju yarn na locale, ale muzeme ho dat asi i do kontejneru

**Comment by marekdedic** [comment]
Jako přímo v tom dockeru? Já totiž v systému yarn mám...

**Comment by sinacek** [comment]
ja si yarn install pustim na localhostu, stejně jako mam kód a pak to cele primountuju do dockeru

**Comment by marekdedic** [comment]
Ok, to předpokládám není popsané v návodu n lokální development, ne? Protože podle toho jsem jel... Tak bych buď přidal do návodu to, co popisuješ (já tomu rozumím tak napůl), nebo přidal yarn do toho docker image

**Comment by juradee** [comment]
Viz #2396 
Vyměněn kontejner.  Nahrazen za thecodingmachine/php:8.1-v4-fpm-node16 který node obsahuje.
