### ISSUE TITLE
Nový docker

### ISSUE THREAD

**Issue by juradee** [skaut/Skautske-hospodareni#2396]
Přenesení stávající konfigurace do nové verze dockerové sestavy. Všechny potřebné programy budou součástí dokceru. Žádná externí aplikace nebude pro spuštění potřeba

- [x] nový docker
- [x] úprava dokumentace
- [x] úprava návodů
- [x] kontrola testů 
- [x] úprava github acitions
- [ ] test nasazení na produkci / test

**Comment by juradee** [comment]
@sinacek 
běžně do sestav dávám pomocné nástroje jako je adminer, mailcatcher,...
Je to OK? Je to chtěné, nebo toto do sestavy nemá přidávat?

**Comment by juradee** [comment]
@sinacek která verze nodu je aktuálně na projektu použitá?

**Comment by sinacek** [comment]
> @sinacek která verze nodu je aktuálně na projektu použitá?

https://github.com/skaut/Skautske-hospodareni/blob/master/.github/workflows/main.yml#L279

**Comment by sinacek** [comment]
> Je to OK? Je to chtěné, nebo toto do sestavy nemá přidávat?

zatim bych to tam nedával, at je to mensí a někdo to můze mít jinak s temi nástroji a jde to pridat jako samostatné image

**Comment by juradee** [comment]
Aktuálně mám skoro dokončené věci, které jsem chtěl s dockerem upravit.

Několik věcí, které jsem potkal a myslím si, že by chtěli ještě dodělat, možná v rámci tohoto úkolu. Dávám k zamyšlení

- dočistit github acitons. Některé věci jsou tam teď asi zbytečně, ale nechával jsem je tam kvůli kompatibilitě a co možná nejmenšímu množství změn
- odstranit phing. Pro běžný provoz jej plně nahrazuje make, pro který není potřeba mít vendor a není potřeba vůbec vstupovat do kontejneru.
- nastavit cache pro kontejneru do github actions. Zde si nejsem jistý jak přesně to udělat a naslepo je to dost pruda.
- odstranit config.ci.local.neon. Kompleně nahrazeno před .env
- odstranit config.sample.local.neon, config.local.neon, config.production.local.neon a ovládat prostředí pomocí .env


Chtěl jsem také předělat dokumentaci na vitepress, vyžadovalo by to další kontejner. Rovnou by to chtělo asi hlouběji aktualizovat a nevím jestli na tohle mám aktuálně energii a jestli je to vlastně žádoucí.

**Comment by juradee** [comment]
@sinacek Jaký je vlastně důvod využívání moje-hospodareni.cz ? Nebylo by lepší směřoval na doménu hskauting.localhost. Odstranilo by to problémy s ssl pro chrome ( testování ), Taky by odpadla nutnost modifikovat věci na hostujícím PC.

**Comment by juradee** [comment]
@sinacek při pouštění coding-standard, stanu a testů se dost liší množství vypisovaných informací, Někde je --no-progress a někde naopak -vv 
Je v tom nějaký záměr?

**Comment by sinacek** [comment]
> @sinacek Jaký je vlastně důvod využívání moje-hospodareni.cz ? Nebylo by lepší směřoval na doménu hskauting.localhost. Odstranilo by to problémy s ssl pro chrome ( testování ), Taky by odpadla nutnost modifikovat věci na hostujícím PC.

Tohle jsme umyslně přesouvali na vlastní doménu, ale uz si nemapatuju ten důvod :/ Můžeme to asi zkusit přesunout na localhost pokud to zjednoduší další věci

>@sinacek při pouštění coding-standard, stanu a testů se dost liší množství vypisovaných informací, Někde je --no-progress a někde naopak -vv
Je v tom nějaký záměr?

Nevím.

Na oboje by si možná pamatoval odpověd @fmasa

**Comment by fmasa** [comment]
K vlastní doméně: SkautIS nepodporoval localhost jako doménu pro přesměrování.

K těm jobům: `--no-progress` se používal pro skrytí progressbaru v CI, jinak většinu logu následně tvoří řádky s progressbarem. Nevím, jestli ostatní joby mají totéž nastaveno, ale cílem bylo mít v CI dost informací, ale tento noise zahodit.

**Comment by marekdedic** [comment]
SkautIS určitě podporuje domény `.test`, tak to se kdyžtak dá použít...

**Comment by sinacek** [comment]
nakonec jsme to museli revertovat, protoze s tim neumel dobre pracovat chrome
