### ISSUE TITLE
Seznam účastníků vzdělávaček obsahuje i nepřijaté bez možnosti filtrování

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2398]
Seznam účastníků VzA obsahuje všechny, včetně těch, co nebyli přijatí - to můžou být stovky lidí, z nichž jenom část je skutečně důelžitá

Buď bych to předfiltroval, nebo přidal možnost si to vyfiltrovat v UI

To samé pro exporty

**Comment by sinacek** [comment]
filtroval bych by default jen prijaté
