### ISSUE TITLE
Notifikační email při změně stavu akce

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#245]
Umožnit středisku nastavit notifikace při různých událostech jako je uzamčení/odemčení akce na email definovaný na středisku.

Není to priorita spíše někdy by to bylo hezké.

**Comment by foglafil** [comment]
ahoj, toto skutečně potřebujeme, platí že priorita je nízká, ale určitě ano. Můžeme ponechat? @sinacek @fmasa

**Comment by fmasa** [comment]
@foglafil, @sinacek Můžeme vyspecifikovat, pro jaký akce v Hospodaření by se to hodilo? Protože značná část jen kopíruje akce ve Skautisu, takže pokud např. uzavřu akci ve Skautisu, tak se o tom nemáme v Hospodaření jak dozvědět.

**Comment by sinacek** [comment]
Ahoj @foglafil , jestli trvá, že by jste to potřebovali, tak nám chybí zadání jak píše František výše
