### ISSUE TITLE
propojení skautIS a h.skauting - zadávání účasti tábory

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2450]
### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. sekce Tábory/ seznam účastníků
2. pomocí tlačítka editovat změnit počet dnů účasti na táboře
_klidně možné vyzkoušet přímo na mé osobě (na tomto konkrétním táboře jsem byla)_

### Očekávané chování
Je umožněno změnit počtu dnů v sekci seznam účastníků, změna se propíše do sekce základní údaje a odtud to skautISu. 

### Snímky obrazovky
![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/d7561cde-50ed-43a4-869a-48094a5d6c79)

### Uživatelské informace:
 - Sekce: Tábory/seznam účastníků
 - Uživatelská role: středisko hospodář/oddíl hospodář/správce akcí
 - Tábor: https://h.skauting.cz/tabory/13761/ucastnici?_fid=nu1f

**Comment by sinacek** [comment]
@ellie-RM nemáš to u tabora, kde jsou aktivní elektronické přihlášky? Je ta osoba přijatá?

**Comment by ellie-RM** [comment]
> @ellie-RM nemáš to u tabora, kde jsou aktivní elektronické přihlášky? Je ta osoba přijatá?

Ano.

Osoba je přijatá, ale je to dospělá osoba, která nevyplňovala e-přihlášku.

**Comment by sinacek** [comment]
U nas je to podle me blokovane, protoze nam to skautis nedovoluje upravit. Obecne co ti nejde zmenit ve skautisu tak nepujde u nas. Vis proc ti to nejde ve skautisu?

**Comment by ellie-RM** [comment]
> U nas je to podle me blokovane, protoze nam to skautis nedovoluje upravit. Obecne co ti nejde zmenit ve skautisu tak nepujde u nas. Vis proc ti to nejde ve skautisu?

nevím, celé e-přihlášky se úplně nepovedly; vložíme to tam ručně

**Comment by sinacek** [comment]
@ellie-RM co s tím dál?

**Comment by ellie-RM** [comment]
@sinacek asi to můžeme pro letošek uzavřít, a doufat, že e-přihlášky příští rok budou lepší ;D
