### ISSUE TITLE
Nesrozumitelná chybovka při ztrátě oprávnění pro posílání e-mailů

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2460]
### Popiš chybu
Z nějakého důvodu se nám odpojil mail, ze kterého jsme chtěli rozeslat info k platbám. To je samo o sobě trochu blbý, ale znám Google API a jeho vrtkavost. Co je ale jedoduše opravitelná věc je nějaká pořádná chybovka

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři platby
2. Spáruj svůj e-mail
3. Počkej 2 roky
4. Zkus odeslat testovací e-mail k platební skupině

### Očekávané chování
Něco jako "Chyba při posílání e-mailu, zkuste ho odpojit a znovu připojit."

### Snímky obrazovky

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/7410ae7c-4356-49ab-898c-1965b21bb1aa)

**Comment by kalich5** [comment]
Taky bych byl pro nějakou srozumitelnou hlášku...

**Comment by sinacek** [comment]
Tohle je hlaska od google kterou jen predam na frontend. Lze ji odchytit a zmwnit ale vse ostatni musi byt predany v původní podobě

**Comment by marekdedic** [comment]
@sinacek A co prostě obalit všechny chybovky od Googlu Něčím jako:

```
Chyba při posílání e-mailu, zkuste ho odpojit a znovu připojit. Interní chyba:

invalid grant => Bad request
```

**Comment by sinacek** [comment]
To nemusí být pravda k čemu je navadis, ale asi to pokryje většinu tak to můžeme udělat

**Comment by marekdedic** [comment]
Souhlas, že to ne vždy musí být pravda, tak navrhuji ještě přesnější:

```
Chyba při odesílání e-mailu. Zkuste ho odpojit a znovu připojit, pokud chyba i tak přetrvá, nahlašte nám ji na XXX. Interní chyba:
```

**Comment by sinacek** [comment]
Asi bych nechal jen 
`Chyba při odesílání e-mailu. Zkuste ho odebrat a znovu přidat. Interní chyba: XXX`

To ze se maji nekam obratit nepiseme u zadne chyby
