### ISSUE TITLE
Načítání osob z registrace 2024 v roce 2023

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2542]
### Popiš chybu
VOJ mají založenou registraci, registraci (registrační kategorie) má založené i středisko. Je založena platební skupina - ale nejde vybírat z členů střediska. Proč?

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. založená registrace střediska ve skautISu na rok 2024
2. založeny registrační kategorie střediska ve skautISu
3. založena platební skupina středisková reg. 2024 - typ registrace
4. přidání plateb (osob) - typ registrace - není možnost vybírat z členů

Otázka je jestli musí být již osoby v registraci vyplněny (ve skautISu), aby se načítaly do h.skautingu?
Nebo modul pro registraci 2024 jde použít až v roce 2024?

### Očekávané chování
Možnost hromadně přidat členy střediska do platební skupiny.

### Snímky obrazovky
Pokud máš, přidej snímek obrazovky. (**Tento Github repozitář je veřejný, nevkládejte tedy osobní údaje**)

![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/891c4299-92af-46db-b9aa-a39d02040f7b)

### Uživatelské informace:
 - Sekce: platby >> platební skupiny
 - Uživatelská role: vedoucí/admin střediska

**Comment by juradee** [comment]
Pravděpodobně nejsou přidané osoby do daných registračních kategorií. V seznamu jsou zobrazeny pouze "registrované"  osoby

**Comment by ellie-RM** [comment]
Aha, to dává smysl, prosím tedy o uzavření tohoto tasku. 
díky za vysvětlení.

**Comment by sinacek** [comment]
@ellie-RM já to tedy zavřu, ale klidně to můžeš příště i zavřít sama, když jsi autor a už ti to neprijde relevantní
