### ISSUE TITLE
nahrávání TP k vozidlu

### ISSUE THREAD

**Issue by ellie-RM** [skaut/Skautske-hospodareni#2543]
### Popiš chybu
V roli vedoucí admin střediska ani v roli hospodář střediska mi nejde nahrát techničák k vytvořenému autu.

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. někdo ve středisku založil auto
2. k autu je vytvořený cesťák
3. chceme dohrát TP, ale není to ten samý člověk který založil auto 
4. proběhne vybrání souboru, ale nenahraje se

### Očekávané chování
Vložení TP k vytvořenému autu.

### Snímky obrazovky
![image](https://github.com/skaut/Skautske-hospodareni/assets/133917699/06098371-4dbd-4423-9ae2-e91c02d780a5)

### Uživatelské informace:
 - Sekce: Cesťáky - vozidla
 - Uživatelská role: vedoucí/admin střediska; hospodář střediska

**Comment by sinacek** [comment]
Vloz id cestaku pls at se muzu pak podivat na kterou jednotku je navazan. A na kterou jednotku je vedoucí /admin

**Comment by sinacek** [comment]
Tak to vypada, že je chyba v JS a nefunguje to tedka nikde.

**Comment by ellie-RM** [comment]
teď jsem to zkoušela například zde: https://h.skauting.cz/cestaky/vozidla/detail/2813

**Comment by juradee** [comment]
@sinacek návrat balíčku Naja na verzi 1.7.0 problém vyřeší. Přechod směrem k verzi 3 vyžaduje netriviální změny

**Comment by sinacek** [comment]
ok, tak to pojdme revertnout. Mam to udělat nebo pošleš PR?

**Comment by juradee** [comment]
@sinacek pošlu během 15 minut. Mám to otevřené
