### ISSUE TITLE
Typ akce má typo "Seminuář"

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2616]
### Popiš chybu
Když zakládám obecnou akci, mám v nabídce "Seminuář":

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/1a27ac2a-ca05-45e6-afc5-0594babc4ac7)

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci Akce
2. Klini na zložit novou

### Očekávané chování
Sminá

### Snímky obrazovky
Pokud máš, přidej snímek obrazovky. (**Tento Github repozitář je veřejný, nevkládejte tedy osobní údaje**)

### Uživatelské informace:
 - Sekce: Akce
 - Uživatelská role: vedoucí/admin střediska 411.01
 - Tábor: https://is.skaut.cz/Junak/Events/Camp/Detail.aspx?ID=4567 ](https://test-h.skauting.cz/akce/new-event)

Zběžne jsem to vystopoval sem, dál na to teď nemám čas. ALe v ISu to typo není.

https://github.com/skaut/Skautske-hospodareni/blob/404839d174a8db3b618dc61a0375f9f2e401638e/app/model/Event/ReadModel/QueryHandlers/EventTypesHandler.php#L21

**Comment by sinacek** [comment]
Našel jsi správné místo, ale ukazuje to, že se to jen přebírá ze skautisu https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Event/ReadModel/QueryHandlers/EventTypesHandler.php#L26 , tedy ten překlep bude podle mě už tam. @manulekonecna muzes to overit s ustredim?

**Comment by marekdedic** [comment]
No minimálně [tady](https://is.skaut.cz/Junak/Events/General/Events.aspx) to je v ISu dobře - ale kdo ví, co se tam děje...

![image](https://github.com/skaut/Skautske-hospodareni/assets/3134692/a4070507-aee2-417e-a696-868628bcf5eb)

**Comment by sinacek** [comment]
<img width="770" alt="Screenshot 2024-02-07 at 11 24 57" src="https://github.com/skaut/Skautske-hospodareni/assets/1140123/861ecacc-25f7-4242-af76-4fe6b8a62701">
V ostré verzi to vidím taky správně, nekoukal jsi na to v testovací?

**Comment by marekdedic** [comment]
Hmm, jo, koukám, že v ostrém h.skautingu je to dobře, já na to narazil v testovacím, když jsem zkoušel něco jinýho...
