### ISSUE TITLE
Nepřehledné zobrazení počtu příloh v tmavém režimu

### ISSUE THREAD

**Issue by romanvajdik** [skaut/Skautske-hospodareni#2635]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.

Zatímco v defaultním, bílém režimu zobrazení je zobrazení počtu příloh jednotlivých (výdajových) pokladních dokladů zřetelné, v tmavém režimu je naprosto nevýrazné.

![issue_zobrazeni_poctu_priloh_tmavy_rezim_evidence_plateb](https://github.com/skaut/Skautske-hospodareni/assets/161230902/2a4cb037-5de7-41ce-94e7-a6a76461f81c)

### Popiš tvůj návrh řešení

Zobrazovat číselné označení počtu příloh pokladního dokladu ve výraznější barvě - kontrastní vůči danému režimu zobrazení.

**Comment by marekdedic** [comment]
Tak by to mělo být opravené, díky za report :)
