### ISSUE TITLE
Pole "Spolucestující" u cesťáku má příliš krátkou omezenou délku

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2707]
### Popiš chybu
Chci si vyplnit cesťák na cestu s 6 spolucestujícími, ale bohužel se mi všichni nevejdou do kolonky "Spolucestující" u cesťáku

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci Cestovní příkazy
2. Založ nový cesťák
3. Piš do pole "Spolucestující"

### Očekávané chování
Měli by se mi tam vejít všichni

**Comment by sinacek** [comment]
Pak ti to asi rozhodí šablonu

**Comment by marekdedic** [comment]
To jsem se taky bál, ale poradí si s tím - vyzkoušno s #2708.

**Comment by sinacek** [comment]
hodis printscreen?
