### ISSUE TITLE
Update Fio api na verzi 4.2.0 do 30. 11. 2024 

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautske-hospodareni#2737]
mhujer/fio-api-php#28

**Comment by banterCZ** [comment]
@sinacek Tohle už implementované? Že už je prosinec 2024 a na přehledu bankovního účtu dostávám tohle, tak jak moc mám hledat chybu u nás.
> Nepodařilo se připojit k bankovnímu serveru. Zkontrolujte svůj API token pro přístup k účtu.

https://www.fio.cz/bankovni-sluzby/api-bankovnictvi

**Comment by sinacek** [comment]
Předpokládám, že ano, protože MR je z května viz výše https://github.com/skaut/Skautske-hospodareni/pull/2738

**Comment by sinacek** [comment]
@juradee @marekdedic muzete to zvednout?

**Comment by banterCZ** [comment]
Vidím, že issue zavřená. Ale jak poznám, že je to už nasazené? Náhled na účet mi pořád nefunguje, tak jestli to znamená, že mám teprve počkat na nasazení nebo hledat chybu s naším tokenem.

**Comment by sinacek** [comment]
po zamergování se to automaticky nasazuje, takze cca do 20 min to je na produkci.

**Comment by sinacek** [comment]
seznam plateb v nastaveni Banky se mi načetl

**Comment by banterCZ** [comment]
Díky za test, bohužel nemám disponentská práva na bankovní účet a admin práva do h.skautingu, tak ověření tokenu deleguji (pak dám vědět). Nicméně doplňující otázka, ten token ze starého API funguje i pro nové API nebo se musel vygenerovat nový?

**Comment by sinacek** [comment]
> Nicméně doplňující otázka, ten token ze starého API funguje i pro nové API nebo se musel vygenerovat nový?
Ja nic noveho negeneroval a nepredpokladam ze by to nekdo u nas stihl udělat
