### ISSUE TITLE
Postupné placení

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#495]
Funkce pro případ postupného placení. Příklad: firmy platí za tábor třeba 2x. Třeba ve dvou měsících po sobě. 

- přidání nového stavu (částečně zaplaceno)
- platby musí mít stejný VS (jen suma jiná)
- kontrolování, jestli je vše zaplaceno (kontrola přeplatků popřípadě nedoplatků)
- možnost dokončit platbu ručně (popřípadě, že hospodář ví, že člen má platit menší sumu př.: bude kratší dobu na táboře nebo jiné akci)

**Comment by kalich5** [comment]
Tak co letošní tábory? :-)

**Comment by fmasa** [comment]
@kalich5 Osobně si myslím, že #923 je maximum, které jsme pro zjednodušení práce s postupným placením schopni implementovat. Je to poměrně okrajový use case (jsi jedinný kdo jej chce) a složitost, kterou to do párování přinese, za tu implementaci nestojí.

Jinak vzhledem k tomu, že s tím do dalšího milestone aktuálně nepočítáme, tak na letošní tábory to k dispozici určitě nebude.
