### ISSUE TITLE
Řazení řádků v závěrečné zprávě, sjednocení se skautIS?

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#509]
Bylo by fajn, kdyby byly položky v závěrečné jinak seřazené (teď jsou např. služby až na konci pod převody, což mi přijde nepřehledné. Dodám přesnější návrh :-) 

Jinak to ještě prodiskutuji s ohledem na skautIS - zjistila jsem, že např. pro zadávání cestovného využíváme 3 pojmy - cestovné, jízdné, doprava materiálu a osob a bylo by hezké to mít více sjednocené.

**Comment by sinacek** [comment]
@manulekonecna budes to tedka resit do konce roku?

**Comment by sinacek** [comment]
@manulekonecna co s tím?

**Comment by sinacek** [comment]
@manulekonecna kdyz se to nevyresi v Q1 tak uz to pak zavřu jako nepotřebný požadavaek když se neřeší
