### ISSUE TITLE
Exporty z hospodaření

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#772]
Uvítal bych možnost vyexportovat si třeba do excelu (na jiných místech to už je) platební skupinu. Obsah té tabulky co se generuje. 

Hlavní důvod je ten, že chceme dát na web tabulku se jménem člena, částkou a VS (vše pod heslem co mají rodiče).

Aby se na to mohli kouknout kdykoliv a nemuseli hledat jaké má jejich dítě VS a kolik má platit. Ty dotazy máme a musíme to hledat, takhle by si to mohli najít sami.

**Comment by YuykaS** [comment]
pokud chci vykopírovat platby z registračních plateb, tak obyčejné kopírování nefunguje (chrome -> excell). buď to neumím dobře vybrat a vloží se mi všechna data do jednoho sloupce a nebo se mi každý záznam uloží na dva řádky. Ani jedno se mi nelíbí... 
Nešla by dát možnost exportu do .csv u všech tabulek? ne nutně jen u plateb?
