### ISSUE TITLE
Čísla dokladů i písmeny

### ISSUE THREAD

**Issue by Huron32** [skaut/Skautske-hospodareni#785]
Zadání: udělat nový prefix pro bankovní řadu

---

Při zadávání čísel dokladů na akce to nechce vzít písmena. Když mám v rámci akce platbu přes banku, tak bych tam potřeboval zadat číslo dokladu, což je pro mne výpis z BÚ, který má označení kombinace písmene a čísla (např. BÚF3 - výpis z března z účtu FIO banky) 

Mohlo by to mít řešení přidat manuálně různou předponu pro číselnou řadu v hotovostní pokladně a na BÚ....ale přijdem i jednodušší povolit i písmena.

**Comment by sinacek** [comment]
prefix pro banku bude vyresen pomocí #1039
