### ISSUE TITLE
Spárované platby - doplnění názvu skupiny

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#816]
Ahoj,
super že vidím že ta platba je spárovaná. Šlo by doplnit k jaké akci je spárovaná? Stačí název platební skupiny. Pomohlo by mi to v orientaci.
![Spárování](https://user-images.githubusercontent.com/8988898/56360766-e6da9300-61e5-11e9-9379-fe4431e2c9c2.PNG)

**Comment by sinacek** [comment]
@fmasa zapoměnl jsem si zapsat k čemu jsme došli. Vyřešíme to tooltipem nad ikonkou?

**Comment by fmasa** [comment]
@sinacek jj

**Comment by fmasa** [comment]
@kalich5 Řeší to tvoji potřebu?
