### ISSUE TITLE
Podbarvení "Dokončených" plateb

### ISSUE THREAD

**Issue by kalich5** [skaut/Skautske-hospodareni#870]
Uvítal bych, podbarvení "Dokončených" plateb.

Ty, u kterých je teď prodleva se splatností se to podbarvuje červeně.

Chtěl bych u dokončených plateb podbarvení "Zelené". Aby to bylo přehlednější.

Děkuji

**Comment by sinacek** [comment]
jsou tam nyní barevné badges pro stavy
