### ISSUE TITLE
Sjednotit mapování a DB

### ISSUE THREAD

**Issue by fmasa** [skaut/Skautske-hospodareni#880]
Momentálně je diffování v migracích opruz, protože máme spoustu tabulek, kde mapování mezi DB a objekty není definováno správně.

Jedná se vesměs o tyto problémy:
- používáme různé typy v DB a v Doctrine -> sjednotit na typ který dává smysl
- máme různě pojmenované cizí klíče -> sjednotit na název automaticky generovaný Doctrine
- používáme unsigned jen DB, nebo Doctrine -> sjednotit používání unsigned
- nemáme definované indexy u entity -> definovat indexy u entity

Díky tomu pak nebude třeba při používání `migrations:diff` odmazávat 90% generovaných dotazů.

` rm -rf temp/cache/*;php www/index.php migrations:diff --filter-expression=~tc_~`

- [ ] ac_ 
  - [ ] ac_object - není v doctrine
  - [ ] ...
- [x] pa_ #954
- [x] tc_ #954
- [ ] vše

**Comment by sinacek** [comment]
@fmasa rozděl to prosím na nové menší issues

**Comment by sinacek** [comment]
@fmasa tady bych potřeboval informaci o stavu

**Comment by sinacek** [comment]
@fmasa tady bych potřeboval informaci o stavu

**Comment by sinacek** [comment]
Přidat novou entitu pro `akci` a pro `tábor` aby šlo napojit namísto ac_object. Presunout data. Inspirovat se `ac_unit_cashbooks`
