### ISSUE TITLE
U role Vedoucí Vzdelavacky se zobrazují i skryté role

### ISSUE THREAD

**Issue by sinacek** [skaut/Skautske-hospodareni#928]
### Popiš chybu
U role Vedoucí Vzdelavacky se zobrazují i skryté role na testovacim skautisu
![image](https://user-images.githubusercontent.com/1140123/60263476-0e826180-98e1-11e9-9031-e6ac04a23838.png)

![image (1)](https://user-images.githubusercontent.com/1140123/60263537-31147a80-98e1-11e9-9382-47957badfa03.png)

**Comment by sinacek** [comment]
zavírám pro nečinnost. Pokud se to bude jeste dít, tak to sem napis a já to otevřu

**Comment by marekdedic** [comment]
FYI, tohle je chyba v ISu, která od té doby byla snad opravená...

**Comment by sinacek** [comment]
Taky je closed
