### ISSUE TITLE
Konfigurovatelné omezení historie bankovního účtu

### ISSUE THREAD

**Issue by vojta001** [skaut/Skautske-hospodareni#948]
### Zakládá se tvůj návrh na problému, který by se tím řešil? Popiš prosím daný problém.

Při účtování letošního tábora jsem několikrát byl v siuaci, kdy jsem se potřeboval podívat na poměrně staré platby na účtu, ať už kvůli účastnickým příspěvkům, nebo kvůli dotacím, avšak kvůli omezení na 60 dnů na detailu bankovního účtu jsem s tím musel za hospodářem střediska.

### Popiš tvůj návrh; řešení

Udělal bych maximální délku pohledu do historie transakcí konfigurovatelnou pro každý účet.

Nemáte-li nic proti, zkusím to naimplementovat.

**Comment by sinacek** [comment]
@vojta001 jak to vidis?

**Comment by sinacek** [comment]
ping @vojta001

**Comment by vojta001** [comment]
Sorry, měl jsem toho hodně. Už jsem přemýšlel nad tím, jak to udělat, ale narazil jsem, že nevím jak to rozumně otestovat; je to externí služba. Pro SkautIS tady máme testovací SkautIS, ale s Fiem? Jak jste to vlastně vyvíjeli?

**Comment by fmasa** [comment]
@vojta001 Potřebuješ mít nějaký Fio účet, na kterém to můžeš testovat. Fio IIRC testovací verzi nemá.

**Comment by sinacek** [comment]
ping @vojta001
