### ISSUE TITLE
Kontrola na shodu výše účastnických poplatků

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#975]
### Zakládá se tvůj návrh na problém, který by se tím řešil? Popiš prosím daný problém.
Vytvořit kontrolu na shodu výše účastnických poplatků na kartě "Účastníci" s evidencí v Evidenci plateb. 

### Popiš tvůj návrh řešení
Vytvoření kontroly - pokud není splněna podmínka rovnosti účastnických poplatků u účastníků a v evidenci plateb. Mohlo by se zobrazovat nahoře u evidence plateb. 

Nekonzistentní data!

Součet účastnických poplatků evidovaných u účastníků není shodný s částkou v evidenci plateb.

**Comment by sinacek** [comment]
@manulekonecna prosím o kontrolu jestli to z tvého pohledu potřeba upravit. Aktiálně tam již hlášku máme. viz <img width="574" alt="Screenshot 2020-04-10 at 20 07 25" src="https://user-images.githubusercontent.com/1140123/79012578-e78ed680-7b66-11ea-9bdd-d747a02d1288.png">

**Comment by sinacek** [comment]
@manulekonecna ?
