### ISSUE TITLE
Chybný výsledek hospodaření na kartě Evidence plateb

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#981]
### Popiš chybu
Na kartě evidence plateb se zobrazuje výsledek hospodaření bez zohlednění vratek.
Týká se pouze Táborů. U akcí by to mělo být správně. 

### Jak chybu nasimulovat
Kroky pro nasimulování chyby:
1. Otevři sekci Evidence plateb
2. A dole na stránce se zobrazí Výsledek hospodaření.
![image](https://user-images.githubusercontent.com/37432874/65026808-8e94f200-d939-11e9-9ee3-a4e5f23c204e.png)

### Očekávané chování
Výsledek hospodaření bude vypočítán jako Výnosy - náklady, nyní nezahrnuje snížení o vratky.

### Snímky obrazovky
Pokud máš, přidej snímek obrazovky.

![image](https://user-images.githubusercontent.com/37432874/65026871-acfaed80-d939-11e9-9a0e-5731949556f7.png)
![image](https://user-images.githubusercontent.com/37432874/65026897-ba17dc80-d939-11e9-94e1-a74092c2afed.png)

Výsledek hospodaření by měl být 1081 Kč.

### Uživatelské informace:
 - Sekce: (příklad: Tábory/Evidence plateb)
 - Uživatelská role: vedoucí/admin střediska 119.67 
 - Tábor: https://h.skauting.cz/tabory/9502/kniha

**Comment by sinacek** [comment]
- když nebude virtuální, tak příjdeme o kontrolu https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Cashbook/Cashbook/Chit.php#L307
- započte se automaticky do nákladů a vypíše se to tam
  - https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Export/ExportService.php#L195 
  - https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Export/ExportService.php#L231
- změní se suma v `FinalRealBalanceQueryHandler`

**Comment by fmasa** [comment]
Ten poslední je to, co chceme. Možná jako dočasný řešení to zpracovávat jen v tom query handleru a dobudoucna to ideálně vytáhnout na jedno místo. Mám pár nápadů, tak třeba z toho něco bude.

**Comment by sinacek** [comment]
- vyřešit obdobně jako hromadný příjmový doklad se přičte do dané kategorie a následně se s ním dále už nepracuje, tedy pomocí `CategoryTotalsCalculator`
- rozdělit vratky u táborů pro děti a pro dospělé, historické nechat jako dětské vratky.

**Comment by sinacek** [comment]
@manulekonecna koukal jsem na to v ostrem skautisu a podlě mě už to funguje správně
